### ISSUE TITLE
Layers Roads of Afghanistan and River network 

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#1]
### Quick check list

- [ ] This isssue is not linked to a dataset
- [ ] This issue is not already discussed in another issue
- [x] This issue concerns a bug
- [ ] This issue concerns a feature request
- [ ] This is VERY URGENT
- [ ] You are a coder and could help with code stuff
- [ ] This project is awesome

### Context

When the layer is deactivated the attributes continue to appear on the map

### Steps to Reproduce

1.
2.
3.
4.

**Comment by fxi** [comment]
Yeah, first issue :)

This concern every view ? Only specific type lines, polygons or point ? This happens only when the view has a style?

Thanks

**Comment by alejandraarango** [comment]
1. There is only one view for each layer, but yes, in both views there is the issue 
2. At the moment, it happens only with lines.
3. Yes, only when the view has a style
