### ISSUE TITLE
Dispaly "Edit source" and "Add view" buttons

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#10]
### Expected Behavior

Display Edit source and Add view buttons

### Current Behavior

This two buttons are not display correctly 

### Steps to Reproduce

1. Login
2. Go to toolbox
3.
...

### Detailed Description

This only happens after login. After refreshing mapx the two buttons are displayed correctly.

**Comment by thomaspiller** [comment]
It happened again today (chrome v60, windows 10 pro). Just after logging in MAP-X, I went directly into the toolbox and the texts were not displayed. No error in the console.

![mapx](https://user-images.githubusercontent.com/19908801/30154295-c562d922-93b9-11e7-8c6e-c15d51b864c4.png)
