### ISSUE TITLE
Bug/suggestion : the content of a story map doesn't adjust automatically to the different screen sizes

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#102]
### Expected Behavior
The story map remains the same as I created it when changing the size/dimension of the screen.
The content of the story map adjusts to the various screen dimensions.

### Current Behavior
When a story map is created, it is created according to the way it is visualized on a certain type of screen. When changing the screen, the content of the story map doesn't adjust to the dimension of the new screen. Example with a text box: when creating the story map, the text fits perfectly to the text box. When switching to a screen with other dimension, either the text font is very little, either it is too big for the size of the text box.
(NB: it is the same issue with all the different content of a story map -photos, videos etc- the content doesn't adjust automatically to a different screen)

### Steps to Reproduce
1. Create a story map using a 4/3 screen
2. Create a text box and adding some text so that it fits perfectly to the size of the text box.
3. Changing the screen to a different one (16/9 for example), the content of the story map doesn't adjust to the new dimensions of the screen: the text is disproportionate

**Comment by fxi** [comment]
I think this is solved. Reopen if needed.
