### ISSUE TITLE
Issue: metadata display does not provide clear information about Data integrity assessment

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#106]
### Current Behavior
As you can see from this figure, it is impossible for users to understand what the numbers mean and what they are for. Unless this is wanted and should not be shown to users, a clearer display of the metadata is necessary.

![integrity in display metadata](https://user-images.githubusercontent.com/30286565/31287771-b8907680-aac2-11e7-8107-c0e4c174f613.JPG)

**Comment by thomaspiller** [comment]
![shutter_20171221_17](https://user-images.githubusercontent.com/19908801/34264451-3ed0e9be-e673-11e7-96e1-0cecc744d0bd.png)

Partially solved. Just need to convert the answers from number to text eg. 0 to "I don't know".

**Comment by antobenve** [comment]
Also in #257 and #284. Closed.
