### ISSUE TITLE
Suggestion: revision of the slide classes management system in story maps

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#108]
### Expected Behavior
It would be better to have more choices for the slide location on the screen, not only the automatic propositions of slide classes based on a 9 parts division screen

### Current Behavior
There are only a few possibilities of slide location since the screen is divided into a 9-parts logic.

### Possible Solution
It could be interesting to have two options: 
automatic classes proposition: a menu similar to the actual slide classes system
manual: a way to manually draw and position a slide on the screen, like a text on Word, allowing to create bigger or smaller slides according to the content needs

### Steps to Reproduce

1.
2.
3.
...

**Comment by antobenve** [comment]
@MarionPlanque , can I close this issue?
