### ISSUE TITLE
[big file upload] Not availed to upload layers.

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#11]
### Current Behavior

Once the layer is dragged in MAP-X the information of the layer is displayed on the map, but is not possible to start the uploading of the layer. The loading bar does not appear.

### Steps to Reproduce

1. Drag any layer in MAP-X
2. 
3.
...

**Comment by fxi** [comment]
Please do not upload superuser password to a public platform...

**Comment by alejandraarango** [comment]
oups! sorry sorry!

**Comment by fxi** [comment]
This revealed a potential threat in the application : passwords should not appear in clear so easily.

I will change this to avoid any further similar issue.

For the upload issue, this is a CSS issue.  

The upload works fine, but the bar does not appear.

Thanks for reporting.

**Comment by alejandraarango** [comment]
Sorry again for the password. I didn't realise that the password was there, I was focus on the map.

For the layer issue, I already uploaded one layer, it works. It's just a little tricky because the metadata window take 1 or 2 minutes to be displayed and the loading bar does not appear so I thought it doesn’t work and I pressed several times on the uploaded buttom. Marion was also confused whit this.

**Comment by alejandraarango** [comment]
I cannot upload any layer. The loading bar appears at 50% for more than 40 minutes and nothing happens then.

**Comment by alejandraarango** [comment]
I cannot upload layers bigger than 83.6 Mo.
![capture d ecran 2017-07-06 12 10 33](https://user-images.githubusercontent.com/28750477/27906637-af174762-6244-11e7-8f9b-48aed2b463ba.png)

**Comment by antobenve** [comment]
I also have a similar problem. 
I tried to upload two .zip shape files of roughly 30 and 90 MB (once compressed). With the lightest file I obtain what you can see in the screenshot (it takes time but it gives this as output) and then the data is not shown in the map. The temporary view is not created.
With the heaviest file I just have a Chrome pop-up saying that the page does not respond.

What can I do in order to load those files? 
![capture upload problem map-x](https://user-images.githubusercontent.com/30286565/28573795-14e05af0-714c-11e7-8ae2-5836b723707f.JPG)

**Comment by fxi** [comment]
There were actually three issue there:

1. CSS/style issue, the progress bar did not show. This is solved.
2. A storage issue, the VM ran out of disk space. This is solved.
3. An issue apparently related to the uploader. Not yet solved.

Could your provide a link to the biggest dataset you need to upload ? If the data is private, you can send me a email with the link.

Thanks

**Comment by antobenve** [comment]
Sure. Writing you an email

**Comment by fxi** [comment]
There is a new (alternate) way to upload "big" files. I already talked about it but here is the details:

What's new :
- More robust internal script
- Native upload process (UI will change later to match map-x one)
- Metadata editable during upload (your computer -> remote server)
- Asynchronous approach : Upload and conversion does not block the whole worker. Which is quite nice for other users.
- Limit features number by postgres transaction, which enable.. Monitoring progress of the importation ! 
- Some minor fixes.

Animated screenshot a general idea of the process (some loading message will be changed) gives: 

![mx_heavy_file_upload](https://user-images.githubusercontent.com/1196833/28752014-99db4d6a-7515-11e7-87e7-c55a04777955.gif)

**Comment by antobenve** [comment]
This is perfect. Thanks.

Antonio
