### ISSUE TITLE
Suggestion: addition of a loading icon on the page during the loading process of MapX content

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#111]
### Expected Behavior
When MapX content takes time to be downloaded, it could be interesting to have an icon flagging the loading process

### Current Behavior
For the moment, there is nothing on the screen telling that some content is loading

### Possible Solution
Addition of a loading bar, a clock, a wheel etc showing the loading process

### Steps to Reproduce

1.
2.
3.
...

**Comment by thomaspiller** [comment]
![image](https://user-images.githubusercontent.com/19908801/34262073-894095d8-e66b-11e7-8c8e-819a43d4a577.png)
Done.
