### ISSUE TITLE
Incorrect pages to Afghanistan

### ISSUE THREAD

**Issue by PeteW-A** [fxi/map-x-mgl#122]
### Steps to Reproduce

1.
2.
3.
...

**Comment by PeteW-A** [comment]
When I am on the page https://www.mapx.org/portfolio/afghanistan_eis/ and click on the link www.mapx.org/afghanistan, it takes me to this URL: https://app.mapx.org/?country=AFG , but the map is of Switzerland.
 
Is it possible to change this to land on a map of Afghanistan.

**Comment by fxi** [comment]
Hi,

I don't manage links on mapx.org/portfolio.

A correct link must specify a "project" or "worker" on app.mapx.org 

E.g. https://app.mapx.org/w5/?country=AFG

Thanks

**Comment by fxi** [comment]
I've done a little change in the server and now we can use the request part of the url directly.  

 https://app.mapx.org/?country=NOR
