### ISSUE TITLE
Add metadata for the views  

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#13]
### New feature proposal

It would be relevant to add a new set of metadata for each view which contains at least:
- author of the view (full name)
- author affiliation
- author contact (at least an email address)
- creation date
- last modified date

### Current state

When we are in MAP-X we have no knowledge of the specific author of each view.
It is therefore difficult to know who to contact if one has a question about a view or even an issue to report to the author.

### Possible Solution
Add a new section in the view metadata
![metadata](https://user-images.githubusercontent.com/19908801/27183580-4d85f7c0-51df-11e7-99a1-8b8408678219.jpg)

### Detailed Description
TBD by the MAP-X team

**Comment by nicolasray** [comment]
This is critical to implement (we often must see the source when we demo MAP-X, we must be able to click on the metadata icon and see it quickly). But I would recommend to do it otherwise: we should decide which of the source metadata item should appear (in plain text, not in "nested-tree" visualization) just below the view name in the metadata windows. The minimum should be the "source" and the "year".

**Comment by alejandraarango** [comment]
Following with the conversation and according to what has been seen in the view configuration process, the following data could be the most relevant to quickly contextualise the layer in the metadata icon. 

Proposal for the metadata view form: 

•	Organisation Name: National Stadistic Office
•	Temporal
Release date: 2009
Last update: 
Range: 2007 – 2008

See image:

The details of the contact information are available in the “Metadata for the source” so maybe it’s not necessary to repeat the information on the view metadata.

Note: For the moment, the organisation name and the Temporal information is in the view title.


<img width="1280" alt="capture d ecran 2017-07-27 17 14 21" src="https://user-images.githubusercontent.com/28750477/28678355-750edcc6-72f0-11e7-8148-ebec85b8b713.png">
