### ISSUE TITLE
Layer does not appear at all or at some zoom levels. Cache in redis issue ?

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#14]
### Current Behavior

The layer « Armed groups – IPIS » in RDC is not displayed.

<img width="1255" alt="capture d ecran 2017-06-22 12 26 56" src="https://user-images.githubusercontent.com/28750477/27429672-319a4432-5746-11e7-84b6-cae02599de63.png">

### Steps to Reproduce

1.
2.
3.
...

**Comment by fxi** [comment]
Seems to be related to cache server side. Again. Same as #12. Hard to tell why it happens.

**Comment by fxi** [comment]
Again. Find why redis-cli does not work properly to cache vector tiles.

**Comment by fxi** [comment]
Should be fixed. It was a new issue with the cache system. Please re open it if needed.
Thanks.
