### ISSUE TITLE
The "print screen" button of views does not always respond.

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#142]
When I click on it I get the loading bar of the screenshot being generated on top of the screen. However, in some cases it closes and the process interrupted without notice.

This happens often shortly after having completed another screenshot with the same button from another view. But I'm not sure if this is a real relation or just a casuality.

**Comment by thomaspiller** [comment]
The "print screen" function doesn't work for views with data near the poles. JTS returns that error:

{pt: g, name: "TopologyException", message: "side location conflict [ (-15.370703953669363, 64.33693909677294, undefined) ]", stack: "Error↵    at rn.c (https://app.mapx.org/test/1.bun…g/test/app.bundle.js:24:455960↵    at <anonymous>"}
message
:
"side location conflict [ (-15.370703953669363, 64.33693909677294, undefined) ]"
name
:
"TopologyException"

**Comment by fxi** [comment]
Ok. This is related to turf or toKml having some issue to convert layers with features near or on poles.

**Comment by thomaspiller** [comment]
The issue was related to the KML export (Turf). Now that the KML was moved to the download function, the print screen seems to work fine.
