### ISSUE TITLE
No possibility to edit story maps under the /test version

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#143]
Under the test version, the edit view box doesn't allow to edit the story map: the box displays the several components of the story map "title", "abstract", "country of the view" etc until "Collections", but the steps are not loaded, therefore there is no way to edit them. 

![bug_sm_test](https://user-images.githubusercontent.com/25179050/32726165-42539fbe-c878-11e7-9402-c92d10bd69e6.png)

**Comment by fxi** [comment]
There is a dedicated button next to the play button to edit the story:
![image](https://user-images.githubusercontent.com/1196833/32726540-9d9e1c5e-c879-11e7-8923-ed98e91f8276.png)
Is this confusing ?

**Comment by MarionPlanque** [comment]
Oh! Ok I see! Well, I would say yes it is, but I wonder if it is actually confusing or if it's just because I've been using the "edit" (pen) function since the beginning, I'm scared not to have an objective and fresh point of view on this one...
