### ISSUE TITLE
Impossible to save edits from a view under the test version

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#144]
Under the test version, when editing a view (vector or story map), it is impossible to click on the "save" button.
The button is grey and the mouse pointer turns into the "forbidden" logo when passing the mouse on the "save" button.
NB: This issue doesn't exist when editing the content of a story map view (under the paper icon, "edit story" icon), the issue seems to come only from the edit-pen button.

**Comment by fxi** [comment]
Have you checked that there is no red warning in titles and abstracts ? Any empty "english" section will block the save btn.

**Comment by fxi** [comment]
@MarionPlanque ?

**Comment by MarionPlanque** [comment]
Indeed, it's the title/abstract combination that was blocking the save mode
Would it be possible to add a little window popping up when trying to save, saying that it's not possible to save the story map unless the title+abstract are fully completed? If I remember well, it used to exist something similar when uploading a new source, like "complete the title and the abstract before saving!"

**Comment by fxi** [comment]
Ok. I've added a bullet point in #135. All modal dialog ( edition window / popup ) will have a list of warnings and errors to explain why something does not work or of if there is an issue.
