### ISSUE TITLE
Story maps: Impossible to activate layers from another country than the view country

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#145]
When creating/updating a story map under a country view, it is only possible to activate layers from THAT country + layers from the world view. 
The correlation of this problem is the following: under the world view, it is possible to activate world layers only.

Under the edit story mode, the layer list proposes all the layers from all countries, any layer can be selected, but nothing appears on the screen when selecting a layer that is not a layer from that country or a world layer.

**Comment by thomaspiller** [comment]
I made some trials and everything works as expected. This issue seems solved.
