### ISSUE TITLE
Take a screenshot not working often in the test version

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#147]
When a view is selected and the archive file with map, legend and pdf wants to be retrieved, the specific option "Take a screenshot" often refuses to work. The process starts (loading bar appears on top of the screen) but suddenly ends before performing the operation.
This occurs quite often and only sometimes can be solved by refreshing the page.

**Comment by fxi** [comment]
Is this related to #142 ? Layer with data near poles ? Please make sure to avoid duplicate and group your issue if you think they are related.

**Comment by thomaspiller** [comment]
No, I had a similar problem for a view in Switzerland -> point dataset with data only located in Switzerland.

**Comment by thomaspiller** [comment]
I took a dozen print screens and everything went fine. This issue seems solved.
