### ISSUE TITLE
Source layers' titles are not updated (if edited) until refreshing the page

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#148]
### Expected Behavior
If I change the title of a source layer I expect that the source layer specified in the view configuration window is up to date. This might be problematic for external users that might think that their editing was not successfull. Furthermore, it can bother users that create a view right after having changed the source layer's title because the wished source layer will be shown with the uncorrect name.
The same thing occurs in the edit source window. After having changed the title of a source layer, this will still be shown with the old name in the list of available source layers to be edited.

### Current Behavior
The updating process takes place only when refreshing the page or changing country.

**Comment by fxi** [comment]
Please keep track of your issues, especially priority 1.
