### ISSUE TITLE
The metadata display layout is not responsive to change of window's size

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#153]
### Expected Behavior
Dragging the vertex of the window where metadata are shown should increase the readibility of the information but it is not. Only white space appears while text remains confined.
![metadata display layout](https://user-images.githubusercontent.com/30286565/33480603-86f9a25e-d691-11e7-894e-6fd71e56b8e4.JPG)

**Comment by thomaspiller** [comment]
Done.
