### ISSUE TITLE
Views and secondary countries: access to edition.

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#156]
As we discussed, it is very useful to be able to edit the views every-time we see them. However, something must be changed in order to avoid potential mistakes such as those experienced the last week when all views could be edited in all countries where they are visible.

Options A (not allowing views edition from all countries):
1) To report the name of the country where the source layer was published. This could be added in the panel of the metadata info of the view.

Options B (allowing views edition from all countries):
1) To access all source layers in every country. I don't know if you want to have this solution as the layers may be several.

2) To block the source layer edition (just read the name of it, but not be able to change it) when the configuration of the view is open in a secondary country. In this way, the views will always be able to be edited for the rights, abstracts,titles and collections in all countries. On the other hand, mistakes will be avoid. 
Only the source layer and the variables must be blocked. However, it will be useful to report the name of the country where these variables could be changed in the view configuration.

**Comment by thomaspiller** [comment]
Option A was implemented.
