### ISSUE TITLE
Registered users can still upload sources

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#158]
I think this is something unwanted as the platform should not be edited by normal users (registered users) but only by publishers upwards.

### Expected Behavior
Registered users may create private or for publishers views but should not be able to alter the platform by adding source layers or even deleting existing ones.
![reg users can upload sources](https://user-images.githubusercontent.com/30286565/33597373-8bb3699a-d99f-11e7-80cb-7ae549390fa2.png)

**Comment by fxi** [comment]
Not relevent : a user should be able to remove or edit a source data uploaded by himself if it's not yet published.
