### ISSUE TITLE
Problem when dragging views on the sidebar

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#167]
### Current Behavior
The problem occur when a view is clicked and dragged along the list of views to change its position. 
It doesn't occur when the list of view is at its original position. It only occurs when the sidebar containing the list of views was scrolled down in a non-original position.
In this case, when a view is selected for dragging, the selected view disappears. It occurs that the selected view is way above in the list of views when the process is terminated. 
If the list of views is scrolled down of a very little amount, we can see the view appearing from above when the pointer is moved towards the bottom of the page. 

### Steps to Reproduce
1. Visualise views list
2. Scroll down the list a little
3. Select a view and drag it down
...

**Comment by fxi** [comment]
Solved in test
