### ISSUE TITLE
Problem when using keyboard arrows to move across story maps

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#172]
### Expected Behavior
When visualizing a story map, the touch of the right arrow should increase by 1 the step number. When touching the left arrow this should move the story map back by 1 step.

### Current Behavior
The right arrow works for a limited number of steps and then stops working. Only the left arrow works at this point (but now always). The left arrow sometimes jumps back by 2 steps when used after the right arrow stops working.

**Comment by fxi** [comment]
Is this still happening on the current /test version ?

**Comment by antobenve** [comment]
Salut Fred,  
  
Oui, c'est dans la version courante sur test que j'ai ce problème. En accord avec ce que j'ai ajouté dans Github il y a 5 minutes, le problème ne concerne pas les stories qui sont crées directement dans la nouvelle version mais seulement celles qui étaient crées dans la vielle version de MapX et n’était pas encore sauvegardé. Il faudrait regarder si le problème persiste quand les stories de la vielle version seront mise à jour pour être bien visualisé dans la nouvelle version de MapX. Je ne me permet pas de sauvegarder une des stories car je suis pas le propriétaire des stories, mais d'après mon tentative de copy-paste du code d'une vielle story map sur une nouvelle vierge story map, j'ai remarqué que la story map que j'ai crée s'affiche bien.  
  
Antonio

**Comment by fxi** [comment]
Ok. Merci pour le test.
Si jamais, répondre par mail produit une copie dans Github. Je poursuis en anglais.

So, we have to update all stories or make them private as soon as /test becomes the main version. Which will happen on monday. I will send by mail a table with all stories name, id, date and last editor.

@MarionPlanque, @thomaspiller : is that ok for you ?

**Comment by antobenve** [comment]
OK Fred. Sorry for the french answer.  
  
This seems the best plan. I think we don't need to set them private but I'll let Marion answer this as she is the creator of them all I believe.  
  
 On monday I will be available for working on some of the story maps if Marion wants to. Let me know Marion.  
  
Antonio
