### ISSUE TITLE
New story map test : first batch of bugs

### ISSUE THREAD

**Issue by fxi** [fxi/map-x-mgl#173]
- [x]  If the editing is canceled using the structure editor while the text editor is active, the "back" button remain grayed out afterward.
- [x]  At visualization users cannot go through the story map by clicking on steps with the mouse. This only applies to story maps that were created under v3. New stories on v4 seem not to be affected by this issue. 
- [x]  A narrow line on each side of the screen is left uncovered by images that are set as "image cover". This result in the map being shown along the narrow lateral space. See figure below.

**Comment by antobenve** [comment]
![story map side space imgcover](https://user-images.githubusercontent.com/30286565/35284328-cb658474-005a-11e8-8b7e-e2db86c593d3.JPG)
