### ISSUE TITLE
MapX crashing in Chrome but not Firefox or Edge (Windows 10)

### ISSUE THREAD

**Issue by davidedwardjensen** [fxi/map-x-mgl#183]
Each time I try to select a menu or move the map in MapX using Chrome (64.0.3282.119 (Official Build) (64-bit), the screen freezes and the browser crashes. I have cleared the cache, disabled all plugins, and reinstalled the programme but this had no effect. I am logged in as a super user. 
Here is a video capture showing all three browsers. I am using a DELL XPS 27 - Windows 10 (i7 7760, 16 gigs ram)

https://owncloud.unepgrid.ch/index.php/s/BK2Tyy8BWJtjDhD

**Comment by davidedwardjensen** [comment]
I was able to some further testing on another dell with a similar configuration. It turn out that the crashing was linked to my superuser status. As soon as I logged out and logged in as publisher, the crashing vanished.

Can you have a look if something changed with the user status for my MapX account (david.jensen@mapx.org).

**Comment by fxi** [comment]
This is not a server side issue. I have very little clues based on what you described.

I think this is related to a corrupted or wrong dataset stored in your browser's local storage. E.g. you drag and dropped a bad geojson or something like this.

Can you open your browser web console on https://app.mapx.org/w1/ and paste this line:

`mx.data.geojson.clear().then(function(d){console.log("done")});` 

Thanks
