### ISSUE TITLE
Extent seems to be out of range error

### ISSUE THREAD

**Issue by davidedwardjensen** [fxi/map-x-mgl#184]
Trying to upload the attached shape files into MapX either as SHP or GeoJSON. I keep receiving error message: Extent seems to be out of range. I have tried to change the extent with QGIS to the viewable screen, but the error still happens. 

[Adeel_Marsh.zip](https://github.com/fxi/map-x-mgl/files/1671699/Adeel_Marsh.zip)
[Al_Izz_River.zip](https://github.com/fxi/map-x-mgl/files/1671700/Al_Izz_River.zip)
[Auda_Marsh.zip](https://github.com/fxi/map-x-mgl/files/1671701/Auda_Marsh.zip)
[Aweena&Gmoogah_Marshes.zip](https://github.com/fxi/map-x-mgl/files/1671702/Aweena.Gmoogah_Marshes.zip)
[Balance_Basins.zip](https://github.com/fxi/map-x-mgl/files/1671703/Balance_Basins.zip)
[Central_Marshes.zip](https://github.com/fxi/map-x-mgl/files/1671704/Central_Marshes.zip)
[Gleween_Marsh.zip](https://github.com/fxi/map-x-mgl/files/1671705/Gleween_Marsh.zip)
[Hammar_Marsh.zip](https://github.com/fxi/map-x-mgl/files/1671706/Hammar_Marsh.zip)
[Haweizeh_marsh.zip](https://github.com/fxi/map-x-mgl/files/1671707/Haweizeh_marsh.zip)
[Sannaf_Marsh.zip](https://github.com/fxi/map-x-mgl/files/1671708/Sannaf_Marsh.zip)

I have 40 shape files to upload - all of them with the extent error. All of the files work correctly in QGIS 2.18.15.

**Comment by fxi** [comment]
First file has this proj4 string : `+proj=utm +zone=38 +datum=WGS84 +units=m +no_defs`and it should be `+proj=longlat +datum=WGS84 +no_defs`.

I guess all the files are projected in UTM, which is not compatible with the maping library we use.

**Comment by fxi** [comment]
I close this, as apparently you found a way to solve your issue.
