### ISSUE TITLE
Screen shot of overlapping views does not generate accurate legend

### ISSUE THREAD

**Issue by davidedwardjensen** [fxi/map-x-mgl#189]
Attached is the outcome of a screen shot using two layers. The resulting legend does not reflect the two input views.
[mx_data_10_10_19.zip](https://github.com/fxi/map-x-mgl/files/1676984/mx_data_10_10_19.zip)

**Comment by fxi** [comment]
The "screenshot" only output the legend of the current view, not all the views legends. All non-related layers will be removed during the screenshot process in the future release. 
Then, duplicate of #163
