### ISSUE TITLE
Fail connection with PostGIS

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#19]
### Current Behavior

I cannot connect to the PostGIS. 

### Steps to Reproduce

1. In QGIS > Add a layer PostGIS 
2. Refill connection data
3. Test connection

**Comment by fxi** [comment]
I know.. I'm waiting on a solution with our VM host provider.. This is not happening in our server.
I will keep you inform as soon as they found a way.

Thanks.

**Comment by alejandraarango** [comment]
This is already working!
