### ISSUE TITLE
Layer rendering (Create a "inverse rendering" option)

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#191]
Datasets with overlapping polygons which style is based on quantitative attributes cannot be properly rendered on map at the moment. An option that allow inversing the rendering order of the polygons would solve the issue. This option could be placed in the style configuration window.
This solution will allow layers with higher values to be rendered above the layers with lower values.

**Comment by fxi** [comment]
Done, will be available in next release.
