### ISSUE TITLE
300M files fail to be uploaded in MapX

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#193]
When uploading a medium-heavy file (300M) the platform is loading but can not complete the process. At some point (around 1 minute) the web page crashes (not the MapX platform, the actual web page) and shows an error message.

**Comment by fxi** [comment]
Thanks for reporting.
Are you trying to upload with the "heavy files" button or using the "drag and drop" method ?

**Comment by MarionPlanque** [comment]
With the drag and drop methid. I try right now to replicate the bug to send a screenshot

**Comment by fxi** [comment]
Drag and drop of a 300MB is extremely ambitious, as it will take more than 3GB of RAM. Your poor little computer will not handle it. The limit was set to 1GB, but it's like waaay to much. I will set it back to 100MB. In the meantime, use the upload button if it's ok for you.

**Comment by MarionPlanque** [comment]
I tried with the upload button, it seemed to work but it is stucked at this step for 15 minutes now:

![2018-02-02_112820](https://user-images.githubusercontent.com/25179050/35728582-544145ae-080c-11e8-8b80-ac4eeaf2d704.png)

**Comment by fxi** [comment]
Wait a little longer, I see postgres running at 100% since 19 minutes, it takes time for complex files. Strange the progress bar did not started, though.
