### ISSUE TITLE
Story map new engine: feedback

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#194]
# Very high priority:

## Autoplay: 
While using the autoplay mode, if you click on step before/after the current step several times, at some point the autoplay is getting lost and either sends on a step that you didn't click on, or  display content that doesn't match with the current step.

## Edit mode: 
It is impossible to edit some text (with the edit tool) if the text in the content box doesn't contain the letter "p" between < and >. The edit tool doesn't display the "orange bar" allowing to edit the text.
![bug1_1](https://user-images.githubusercontent.com/25179050/35730432-69eb8666-0812-11e8-9039-96919285483b.png)
![bug1_2](https://user-images.githubusercontent.com/25179050/35730444-70a1f7b0-0812-11e8-9da1-dd3fb8861ac3.png)

It works only if the user adds a "p" in front of the text in the content box.
![bug1_3](https://user-images.githubusercontent.com/25179050/35730451-75bf7e02-0812-11e8-8177-117febb2d0e2.png)
![bug1_4](https://user-images.githubusercontent.com/25179050/35730454-7a3eaca0-0812-11e8-8ff7-72ac4d49ea05.png)

# High priority:

## Preview button:
The preview mode cancels the current parameters of the map and sends back automatically to the parameters defined in step 1 (position of the map + view activated)
The user has to click on a step before the current step to retrieve the map parameters that have been defined.

## Image cover:
The image cover is not fully "cover": it stops 2 or 3 pixels before the right side. 

## Edit tool: 
When the side class box is empty, the user must move the mouse towards the first raw of the slide class to highlight the orange bar allowing to edit content. 
This is not very clear: it would be easier to activate the edit mode by clicking anywhere in the slide class box
![bug2_1](https://user-images.githubusercontent.com/25179050/35730895-138d0a40-0814-11e8-971f-d63e5b3621ea.png)

# Medium priority:

## Various MapX sessions opened:
It is not possible to upload an image if an other MapX session is opened at the same time **or** if the current MapX page has not been refreshed after the other MapX page has been closed. 

# Suggestions:

- "Views to activate" and "Map position" items should go back at the top of the step window (see the previous version of the story map engine). It is easier because the user defines on a first hand the map parameters, and on a second hand the narrative supporting the map.

- A drag and drop functionnality for the photos should be possible

- Under the edit mode, the "image parameters" button located on the bottom left side of the screen is not visible enough. It would be better to delete this button and to associate the content with another edit box. 
Ex: click on the photo and a little "edit photo" window pops up, like the text one on the left side of the screen.

- Transparent logos: under the edit mode, transparent logos have a black background. This is a bit confusing for the user who may think that the transparent background has not beensupported by MapX.
 
- The main "story map edition" window is a bit too high for the screen and not easy to be reduced (only with the bottom-right corner of the window)

- The size of the automatic titles should be slightly increased to have a real difference between header 1, header 2, header 3, bold caracters and normal font.

- The citation mode that existed in the previous version of the story map engine should be available in this version too with the same layout.

- There is no possibility to access the Json code of a step, only the slide's one.

**Comment by fxi** [comment]
### Same as above, as todo list

- [ ]  User wants to add text in the structure editor instead of using the direct editing. Add paragraph element during the story building if so.
- [ ] Check stability in autoplay mode: if the user move around using arrows or buttons, autoplay should stop be cancelled. (@MarionPlanque, is it happening in /test also ? )
- [x] As before, the preview button should keep the story scroll position. (already done in local)
- [ ] Add multi session token support in VT
- [x] Full width image cover : Hide webkit/blink scrollbar completely in story map mode.  (scrollbar will still be there in Edge,firefox, or non webkit browser)
- [ ] Better highlight of edit zone in empty slide
- [ ] Add image drag and drop, as in previous version
- [ ] Edit elements buttons in the bottom of the view port is not visible enough. Edit in popup would be better
- [ ] Remove image black background for transparency in edit mode
- [ ] Add a half or quarter screen mode button in modals
- [ ] Add more variation between h1, h2, h3, p, etc..
- [ ] Add citation mode
- [ ] Add edition as json at step level

**Comment by MarionPlanque** [comment]
Check stability in autoplay mode: if the user move around using arrows or buttons, autoplay should stop be cancelled. (@MarionPlanque, is it happening in /test also ? ): Yes, it is the same issue under the test version

**Comment by MarionPlanque** [comment]
@fxi I just realized that in my "edit mode" comment, under the Very High Priority tag, I was refering to the so-called "anchor", which is a "p" between the symbols < and >. For some reason when I type this combinaison in github, it doesn't appear on the screen (meaning my sentence was not ended and didn't mean anything). I hope you managed to understand what I was refearing to!

**Comment by fxi** [comment]
No update on this, reopen it if needed.

**Comment by MarionPlanque** [comment]
Bug solved indeed!
Tomorrow I'll make you a new post about updates on the previous bugs and new bugs
