### ISSUE TITLE
Language functionnality: the MapX page needs to be refreshed to see the language modifications

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#195]
The MapX page needs to be refreshed to take into account a new language parameter
Ex: MapX language is automatically set on English: to translate MapX into French, language button --> French --> ok, but nothing changes on the platform. The user needs to refresh the page to see this modification.

**Comment by fxi** [comment]
Is it happening in /test ?

**Comment by MarionPlanque** [comment]
No indeed, problem solved under the test version
