### ISSUE TITLE
reorder the list of available countries

### ISSUE THREAD

**Issue by nicolasray** [fxi/map-x-mgl#21]
In the list of available countries, after Liberia we should see:
Somalia
South Sudan
Irak

These are the three likely next countries for which we are going to populate data sets
You should also remove "Palestinian territories", Portugal", "Russia", "Japan" and "Jersey" from the top of the list and place them back in alphabetical order

**Comment by fxi** [comment]
I will try to find a way to specify the order in config file

**Comment by fxi** [comment]
Order is now defined
1. By available (non global or shared) view count for a given user
2. Then alphabetically
![mx_country_list](https://user-images.githubusercontent.com/1196833/28715781-e406b258-7399-11e7-8f06-2905fe6a3140.gif)

I really try hard to avoid hard-coding thing. Common logic is a better approach: more flexible.

If you really want a custom order, please provide a complete list of country based on ISO 3166-1 alpha-3 norm.
