### ISSUE TITLE
Sources validity: strategy to avoid PM2 errors

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#215]
## To do list

- [x] Asynchronous upload in the node/express app + build of a validity report for the uploaded file
- [ ] If a geometry is not valid, try  autocorrections in PostGIS or delete the source.
- [ ] Add a try/catch to verify the tiles validity before their rendering. In case of an error, render an empty tile or a tile with a red cross. [note] case when an updated geometry become corrupted afterwards. A report should be also be made.

[edit by @fxi]

**Comment by thomaspiller** [comment]
linked to #214

**Comment by thomaspiller** [comment]
@fxi Hi, fxi is this issue still relevant as PM2 is no longer part of the MapX stack?

**Comment by fxi** [comment]
PM2 was the process manager. Maybe you had in mind TileSplash, the library I used after PGRestAPI to build tiles ( and before postgis then geojson-vt ). However, the second issue should be solved by 1.5.40.1 and the third one seems related to rendering, which is done client side. Not completely clear what was the context of corrupted geometry afterwards... Long story short, yes, you can close this issue.
