### ISSUE TITLE
Story map: Videos keep playing when switching to another step 

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#216]
The video in a story map keeps playing when switching to another step (see the MOOC Colombia story map).
Suggestion: a click to another step should pause/stop automatically the video

**Comment by fxi** [comment]
It's not a bug : the video component is not handled by mapx : reporting a bug to youtube could be a better idea.

We could handle html5 video and detect if it's out of the viewport, but there is no official support for it, so, for now, the user should press the stop button.

**Comment by MarionPlanque** [comment]
Actually, this "issue" was problematic when using videos coming from another web server than youtube (owncloud for instance), but youtube videos should be ok: the users are used to interact with youtube videos in general

**Comment by fxi** [comment]
I just found that we can control youtube video in iframe from outside.  So, as we already stop animating stuff when the slide is no longer visible, we could add a rule to stop sounds and videos at the same time. Note for myself : the postMessage interface could be used: https://codepen.io/smonn/pen/gaeVae
