### ISSUE TITLE
KML files still triggering a bug report when uploaded

### ISSUE THREAD

**Issue by davidedwardjensen** [fxi/map-x-mgl#220]
I am still having the same problem with KLM files when trying to manually upload them in MapX. It triggers a bug report from the developer and they do not upload. However, when I drag and drop them into MapX, it works.

**Comment by thomaspiller** [comment]
Small summary of KML management in MapX:

- The only solution to ulpoad KML files in MapX is the drag & drop method.
- Multi-Layer KML Files are not supported.
- _Add a source layer_ (toolbox) is only compatible with GeoJSON.

**Comment by fxi** [comment]
I close this issue, has it's not directly related to MapX code.

We could explain it better, but if the user modify his/her browser to enable non-valid dataset to be uploaded, we can't do anything : file validation is not done client side.

If the user upload a non valid format, for now, we block it and report what happen to the developer.  The user has only a standard error : it's not supposed to get there. 

We could show a message more explicit.
