### ISSUE TITLE
WMS layers are not loaded in custom views if connected outside GRID

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#222]
The "Mogadishu urban growth - landsat imagery (2001 - 2018) view is not properly working if we connect to MapX from a connection other than the GRID one. Marion and David reported the problem and I confirm that I cannot load any map from my house.
These are the console screenshots:
![console custom view wms 1](https://user-images.githubusercontent.com/30286565/37700204-e7464cf2-2cea-11e8-89c4-f3b98e0efa90.JPG)
![console custom view wms 2](https://user-images.githubusercontent.com/30286565/37700206-e9707156-2cea-11e8-985b-c30089024a3d.JPG)

**Comment by fxi** [comment]
I'm working right now on it from my house without any issue.
Are you reading your emails ?

**Comment by antobenve** [comment]
The problem occurred yesterday evening at Marion's and David's, when you 
were not working on it and when I was able to visualize the images on my 
computer. Thus, if you thought the this report was useless cause the 
error at my place was due to you working on it, consider that it is 
instead a real issue for some computers, at least at UNEP.


Antonio

**Comment by fxi** [comment]
@antobenve Please :
- Try to avoid naming people without letting them know : use @ 
- If you think this unfair,  consider rewrite a new issue, or reopen or edit this one to add related material : paste of your logs or link to a GIST. As asked. This is not difficult.
- For this particular case : there are some bugs in the current version of the custom code evaluator, yes, but nothing to do with network issues. Unless you bring some evidence of that.  The custom code itself could have some issues too, but it's mostly not related to map-x.

**Comment by fxi** [comment]
The other bug is a probably old bug never reported – probably because never encountered –
Follow up in #223
