### ISSUE TITLE
Rendering problem with exhagons when multiple views are on map

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#226]
![image](https://user-images.githubusercontent.com/30286565/38089298-459c0efc-335f-11e8-991b-1317f104fef6.png)

- Multiple views are on in AFG. One of them is the "conflict density" which consists of exhagonal polygons.
- Every view that sits below "conflict density" (views panel order) has exhagonal polygons drawned on it. 
- The exhagons disappear when "conflict density" is switched off and re-appear if the view is on again.

**Comment by fxi** [comment]
Ok.

I'm not sure to understand the issue. 

Could you please explain what you are expecting and what is happening, in a few words ?

**Comment by antobenve** [comment]
There are hexagons on top of polygons and points that should not exist. They appear as symbols of other features by the activation of the view that has haxagons polygons.
If you enlarge the figure you can notice that the large rectangle-like polygons (but also rounded points although they are less visible) have hexagonal symbols on them.

**Comment by fxi** [comment]
Ok, I get it. 

I will translate that in my words:

- Transparent polygons edges are visible.

Thanks.

**Comment by antobenve** [comment]
I close the issue because it seems that this specific problem was related to the combination of data (that consists of hexagons covering all the available surface of AFG that were set very transparent) and the layers rendering order issue in #227
