### ISSUE TITLE
Story map: picture not taking full width of the screen

### ISSUE THREAD

**Issue by nicolasray** [fxi/map-x-mgl#23]
### Expected Behavior

if I resize my window, especially on large screen, I want the picture to span the full width, whatever the height of the screen

### Current Behavior

It looks OK when the window is small/medium, but on my big Mac screen it does not span full width

### Steps to Reproduce

1. Fist slide of the AFG story mao, with the picture
2.make your browser window full width, but small height
3.
...

**Comment by fxi** [comment]
Done. Tested on safari 10.1 and chrome 59. Report here if any other browser has issue.
