### ISSUE TITLE
List of developments for UNDP - JULY and later

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#235]
**Priority 1**
**End-June**

- [x] Filter views by max role  ( `?filterViewsByRoleMax=public` --> only public read fetched. `?filterViewsByRoleMax=publisher` --> public, member and publisher view fetched.  ~Filter views by target in url ("target=public, publisher" --> only public views and views for publishers will be available in the iframe)~ 
- [x] “Add data to my sandbox” button for a view should allow to select the destination sandbox.
- [x] Remove the list of names and affiliations from MapX for privacy reasons when giving access to projects, sources and views.
- [x] `showProjectList="text_in_name_of_the_project"` --> List of projects is filtered according to a string that is contained in the name of the project (the way it is in english). [see wiki for actual implemenation]
- [x] Switch order of projects in panel from "number of views in it" to "alphabetical order" and keep the projects where the user has a role in on top.
- [x] Change log-in icon.
- [x] Download as SHP should not be removed -- most of our clients work with SHP
- [x] Allow users to become members of a public project 
- [x] "Display only selected" is more visible. Next to search box? ***[moved to Sort by...]***
- [x] Clip national borders with UN borders when downloading data (upon UN agreement on dataset)
- [x] Moving and dividing the main toolbar into 2 clusters – top left, top right. Move the map related buttons to the top-right corner of the screen (Orientation of the map, Switch to satellite, Zoom in, Zoom out)
- [x] Toolbox --> Database : the button « Get a temporary access » is not clear enough. Change to "Get a temporary access to edit a dataset"?
- [x] Change filter by type from (raster, vector, custom, story) to (layer, dashboard,  #story).
- [x] ~~Change ON-OFF views' button: what is requested by the client is a **white to green switches**, that move left to right (not eyeball to cross eyeball)~~
- [x] ~~“Sandbox” pop-up window is forced through url statement (“`showProjectList=True`”). It offers links to  each available sandbox of the current user where he is at least member.~~
- [x] ~~Force LOGIN if "SetSandboxPopup=True” is stated in the url and no user is logged in when MapX opens~~ 

**Priority 2**
**From July 2018**

- [x] Change landing page from DRC to WLD.

- [ ] Change the style of the interface slightly (darker colors?) for the project pages where the user has some roles (to enhance the difference between their project and other projects)
- [x] If possible, allow an admin to enter an email that was never used in MapX in the "Role Administration" window of a project. --> create the account directly when the email is used in the project roles window.

**Priority 3**
**For end of 2018**
- [ ] Kiosque mode/autoplay for view-layers (must be interoperable with requests of more than one view too).
- [ ] Splash screen (for simplified interface of MapX that can be customized to each project)

- [ ] All other elements in https://github.com/fxi/map-x-mgl/issues/212

**Comment by thomaspiller** [comment]
@fxi Don't forget that there are two "Priority 1" developments to do before the release of V5.

**Comment by antobenve** [comment]
@fxi Don't also forget the temporary overlap analysis through button that overlap all active views client side.

**Comment by antobenve** [comment]
I'm closing it as we continue on #212. 
Most points in here are accomplished. Those that are still not are either in #212 or not for 2018.
