### ISSUE TITLE
Type of data in MapX metadata

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#240]
Add a key/value couple in MapX metadata for: "type of the data" - vector or raster.

**Comment by thomaspiller** [comment]
@fxi Do you remember why we wanted to add this key in the metadata?

**Comment by fxi** [comment]
Nope, no clue. It was maybe a hot day. Not even close : 24°C, mildly cloudy. 

The type is already set in parent level in mx_sources. 

The idea of mx_sources was to register any external or internal sources, raster or vector: so no need to repeat that in meta. We should register raster source, though.
