### ISSUE TITLE
MapX Version 5 - Specific visual identity for the private sandbox

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#242]
**General feedback after the MapX V5 presentation:**

Currently, there is no difference in terms of visual identity between the general MapX projects (the public ones) and the projects in which users have special rights (publisher, administrator etc).
It can be confusing for the users to understand if they are visiting the page of a general project or a "private" one.
There should be a distinct visual identity between the two of them.
_Suggestion_: A difference of color in the platform between the two types of projects: normal MapX visual identity when users are visiting "public" projects, and another color scheme (maybe the black version of MapX?) when the users are visiting a project in which they have special rights.

**Comment by thomaspiller** [comment]
Duplicate from #235
