### ISSUE TITLE
Github - add a new tag to differentiate private feedback from general MapX team ones

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#243]
Currently, on Github, there is no way to tag a post according to the source of the comment.
It would be interesting to add two new tags: "private comment"/ "team feedback" to differentiate the personal comments from the team ones in order not to overwhelm the developer with personal comments.

**Comment by thomaspiller** [comment]
@fxi @PierreLacroix  Should I add two new labels: official & personal (or something like that)?

**Comment by fxi** [comment]
This issue manager is meant to be public and transparent, code-related, so it's irrelevant to post private messages. 
Using Slack give us plenty of possibilities to link issues to our github issue manager, sending private messages, and so on.  The only concern I see here is that our slack project is linked to a specific project and may be inadequate for general MapX related issues and discussion. But we can easily overcome this and keep one workspace with distinct channels for each project. See with @scabecks to check if that possible.
I close this issue for now, reopen it if needed.
