### ISSUE TITLE
MapX v.5 testing - bugs

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#244]
## Priority 1 (for July 03)

- [x] add a new view: disconnected from server for all types, except story map
- [x] edit view: disconnected from the server when saving a view
- [x] delete source button is grayed out for sources added in V5-> deletion is not possible
- [x] new story maps: no button "edit story map"
- [x] new story maps: MapX crashes when clicking on "save" in the edit panel : disconnected from the server
**NB**: for the already existing story maps, everything works perfectly
- [x] world project: the platform doesn't load: loading process blocked at "Fetch views 284/294" -or different- but never loads all the views (other projects are ok). The problem remains the same whether the user is logged in or not
- [x] Here.com credentials must be updated
- [x] share view: The "share view" button doesn't work: the link sends to the landing page (DRC) with "No view available" in the panel
**NB**: the share view button works **ONLY** for views of DR Congo
- [x] url to open specific projects: opens DRC if the user is not logged in (although the projects are public)

**From MarionPlanque**

_Views_
- [ ] **Interactive variables**: @fxi  When clicking on the data displayed on the screen, if the name of the variable is too long, it's not sent to another lign but it continues on the same lign and hides the values of the variable:

![image](https://user-images.githubusercontent.com/25179050/42240830-e3131d8e-7f08-11e8-954e-5e82de3fa957.png)

_Private sandbox_
- [ ] **Configuration of a private data sandbox**: @fxi  When editing the map parameters of a private data sandbox (in the "configuration" window), it is impossible to interact with the map: neither with the mouse nor with the map buttons of the menu (zoom in/zoom out) works. The only way to edit the map parameters of a sandbox is to **FIRST** define the map position outside of the configuration window and then, use either the button "use current map parameters" or type the coordinates in the latitude/longitude/etc boxes. 

_Upload NEW data_
- [x] **Configuration button**: MapX crashes when clicking on "save": disconnected from the server
- [x] **Legend**: MapX crashes when clicking on "save" (all the rest -preview included- is fine): disconnected from the server
- [ ] **Upload data**: @fxi  Once the data have been 'temporarily' added to MapX by drag and drop, MapX crashes when I click on the button "Upload".

_Story Maps_
- [ ] **List of views accessible when creating a story map**: @fxi  There is no longer the ISO code indicating to which country the data layer belongs, however, it has been replaced by the MapX ID of the view; _ex_: (MX-TKA-1FQ-5ZB-ADF-NBY) Areas of interest for mining activities
- [x] **Autoplay mode**: @fxi  story maps in the autoplay mode don't display any data (but text and multimedia content is fine)
- [x] **Story map edition**: impossible to edit a story map (the "edit story" button): MapX crashes when the button is clicked
- [x] **Adding photos**: @fxi when editing a story map to add a photo, once the photo has been uploaded in the "text box", impossible to click on "insert" to finalize the operation. Only "clear" can be clicked.

**IMPROVEMENTS**
- [ ] **Upload new data**: ~there is no difference in terms of visual identity between the data that have not been uploaded yet in MapX  and the data that have been uploaded as sources (in MapX V4, the orange circle was outlining the temporary data)~ [ related to a test, no final version ]
- [ ] **Delete project**: @fxi  Currently, the exact name of the project to be deleted has to be written; it's not very convenient as a mispelling can occurs (accent, space etc). A drop-down list of projects that can be deleted according to the user's rights would be better. 

**From antobenve**
- [ ] "Share" button of a view only workd once. If it is clicked, then the popup window is closed, and the "Share" button is clicked again --> the pop-up window is not loaded again.
- [ ] use of particular characters such as [', ô,......) is not accepted in a project's title. It should, because projects with such names already exist (see UNBiodiversityLab - Côte d'Ivoire)
- [x] Edit project's title is not possible if the project is public. The project must be turned private in order to edit its title and then public again.
- [ ] WMS generator in raster view responds with "null" when layers are demanded.
- [x] Self-published source layers cannot be deleted. (Views can instead --> OK)
- [x] Set project "public" is in both "Define role" and "Project configuration". Remove it from the first (preferentially).
- [ ] Increasing the size of the panel that contains the list of available projects doesn't enlarge the list but only adds white space in the pop-up window.
- [ ] `https://mx.app.fxi.io/?project=ID` doesn't open the selected (public) project if the user is not logged in. [*duplicate*]
- [x] Custom code views are not working (no data is shown on map)
- [ ] Story maps with read access != "public" cannot be opened by public users when they are shared with the specific url
- [ ] public story maps that were published in a private project are also not accessible when shared with otherusers.
- [ ] long legends of raster views display extended when the view is activated. When the view is switched off and on again, the legend loads correctly (embedded with scrollbars)
![image](https://user-images.githubusercontent.com/30286565/42282431-c94331d4-7fa6-11e8-91ac-2503f423b792.png)
- [ ] Publishers should be able to create a new collection in the configuration window of a view that they can edit. Only admins of the project where the view is can at the present state.

**From thomaspiller**
***Bugs***
- [ ] ~view toolbar: move to bottom doesn't work~ [ related to a draft, does not apply in main]
- [ ] ~view toolbar: move to top -> click -> view moves one position up~ [ related to a draft, does not apply in main]
- [ ] sort by title: doesn't work properly after changing the UI language - still sort views according to the first language
- [ ] take a screenshot: mx_north_arrow.png is missing
- [ ] metadata: DIAF answers are integer (0 to 4) and not text label (Yes, No...)

***Improvements***
- [x] long project title -> 2 lines -> language selector + filter views have lot of white space
![image](https://user-images.githubusercontent.com/19908801/41922465-6ba82274-7965-11e8-8ab4-b1f586d4092c.png)
- [ ] sort by ...: no indication of which filter is active (possible solution: color of active filter = red)
- [ ] only the highest privilege should be displayed in the UI
![tempsnip](https://user-images.githubusercontent.com/19908801/41925050-c3713d28-796b-11e8-8b7f-9cd6f9bc2870.png)
- [ ] MapX toolbar: tooltip label is missing for the "information button"
- [ ] left panel: "Filters >" is not vertically centered
- [ ] left panel + popup: check boxes are not vertically aligned with their label

**Comment by MarionPlanque** [comment]
@antobenve : "The data is not visualized on map when a geojson is dragged and dropped on map. The data is only shown when the layer is uploaded into the database." : everything seems to work on my side

**Comment by thomaspiller** [comment]
FYI, I did the "fixtureData" test: 2 files couldn't be added on map: cod_basins_complex.zip & cod_biodiv_db_missing.zip

**Comment by fxi** [comment]
@thomaspiller, is this failing without any meaningful error message in a modal panel like "No  DBF/PROJ file found in the archive" ? Because that kind of error is expected : if there are missing files in the archive, MapX could not yet rebuild them from thin air.
Jokes aside, if there is no meaningful message, what are the logs saying ?

**Comment by thomaspiller** [comment]
@fxi: As you expected, the following message appears for both sources:
![image](https://user-images.githubusercontent.com/19908801/42078501-0e27d35a-7b7d-11e8-977e-ed801915c614.png)

**Comment by thomaspiller** [comment]
Remaining bugs were split into multiple issues #255 #256 #257 #258
