### ISSUE TITLE
Legend + abstract too long -> buttons hidden

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#253]
Example:
![image](https://user-images.githubusercontent.com/19908801/42926883-ff9c663c-8b32-11e8-8038-6c498837f856.png)
https://mvp.app.mapx.org/?views=MX-SJA01-N84EY-JBK5R&project=MX-XNI-RMZ-KKL-FMS-DVH

**Comment by fxi** [comment]
done, soon available in testing
