### ISSUE TITLE
Bug: MapX disconnecting when creating a sandbox

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#259]
MapX disconnects when a new project is created:
Add new project - Title - "Create" --> MapX disconnects when clicking on 'create'

**Comment by thomaspiller** [comment]
I created a new project this morning (Minamata...) and I had no disconnection issue.

**Comment by MarionPlanque** [comment]
I created some this morning as well and it was working too. It doesn't anymore

**Comment by fxi** [comment]
Solved.
