### ISSUE TITLE
Button "About": inconsistency 

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#262]
The tool tip for the About icon says BTN_About. The other tool tips don't use the prefix BTN. 
The tool tip should say "About MapX"

**Comment by fxi** [comment]
This is because it has no translation in the dictionary : if it has an underscore, its a key...
I've added that to the dictionary.

**Comment by MarionPlanque** [comment]
@fxi Do you have an agenda for when the changes and bugs you fixed will be pushed or not? For instance, this button thing will be part of a larger set of improvements that will be all pushed at the same time or do you plan to push them little by little?

**Comment by fxi** [comment]
No need to reopen this, you can just comment :)
As there is no milestone on those issue and none are really "blocking" – from what I've seen –, consider that it will be available soon. Soon, as in mid-august "soon". Maybe after that, for some changes. Maybe sooner.

**Comment by MarionPlanque** [comment]
test
