### ISSUE TITLE
Impossible to log in: error message

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#272]
Once logged out from MapX, it is not possible to log in anymore: an error message appears saying it is not possible to send the email containing the password (see below).
![bug log in](https://user-images.githubusercontent.com/25179050/43573447-05d52ede-9642-11e8-84a8-a8333841b02c.PNG)

**Comment by fxi** [comment]
Solved, please close this if this works for you.

**Comment by MarionPlanque** [comment]
Merci!
