### ISSUE TITLE
Vector views: "information" button doesn't work

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#274]
For vector views only, MapX generates a bug when clicking on the "information" button.
The error message says the following: 

> Something went wrong :/
An unexpected issue happened : our team has received a notification about it. If this keeps happening, you can also post something here:
https://github.com/fxi/map-x-mgl/issues
More info
>

**Comment by fxi** [comment]
Could you test the at https://test.app.mapx.org ?

**Comment by MarionPlanque** [comment]
@fxi  the page doesn't open properly, it is blocked with an empty view menu

**Comment by MarionPlanque** [comment]
All good, I close the bug
