### ISSUE TITLE
Configuring View disconnects from server

### ISSUE THREAD

**Issue by scabecks** [fxi/map-x-mgl#275]
When attempting to configure a View (any view), but specifically using a recently uploaded source file (ProtConn) I am immediately disconnected from the server. No alterations to the view are made or saved. Trying again results in the same disconnect.

**Comment by fxi** [comment]
It seems to be solved by commit 9422ab0
Could you try on https://test.app.mapx.org ?

**Comment by scabecks** [comment]
On https://test.app.mapx.org I am unable to get a list of views to show for me test on. Same disconnect on https://app.mapx.org/ as before as well.

**Comment by fxi** [comment]
app.mapx.org is not yet updated, I'm doing "live" test in test.app.mapx.org. This is not a permanent service and it will be updated very often. 
Could you please try again ? I've made a mistake in my last push, it should be solved.

**Comment by scabecks** [comment]
Perfect. No issues with it now there.
