### ISSUE TITLE
Legend expansion in list of views

### ISSUE THREAD

**Issue by GianlucaGygax** [fxi/map-x-mgl#276]
When the text of the legend is too long in the list of views, it is abbreviated with ... (e.g. Area de Proteccion de Flora...) When expanding/increasing the size of the list of views, the abbreviation persists although there would be enough space. It would be good if the legend is responsive and automatically displays the entire legend. This enables taking screenshots of the full legend which is essential for integrating them as images in story maps.

**Comment by fxi** [comment]
By expanding the size, you mean using the bottom right corner to resize the views container ?
Could you you share a link ? If this is private content, you can use email or slack.

**Comment by GianlucaGygax** [comment]
Yes, i mean using the bottom right corner to resize the views container. 
Example: Project: UN Environment Story Maps > View: Areas Naturales Protegidas Federales de la Reupblica Mexicana (CONANP 2017).
This is just one example where the legend is too long.

**Comment by fxi** [comment]
I've fixed this in 60c3fd, have you seen it ?

*Demo*
![mx_labels_responsive](https://user-images.githubusercontent.com/1196833/43772603-f0cee3d6-9a42-11e8-93be-14f26fd26bb5.gif)
