### ISSUE TITLE
I cannot login to the platform 

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#28]
### Current Behavior

I cannot login to the platform 

### Steps to Reproduce

1. Open login window
2. Enter e-mail
3. I didn't recibe the password in my mail. I tried 5 times
...

**Comment by fxi** [comment]
Possibly related to a server side issue : does not seems to be related to the application itself.
I've reloaded the applications server and modified some network rules.
Can you try again ?

Thanks.

**Comment by alejandraarango** [comment]
It works, thanks.
