### ISSUE TITLE
MapX doesn't load properly on Mac: info on problem

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#283]
## To sum up:

- The concerned OS are High Sierra and Sierra.
- The only error reported is webgl=false in the test.
- Users with this error clearly can't open MapX in any way.
- One user can't visualize the MapX i-frame from unbiodiversitylab.org. **No error reported in this case (webgl=true)**
- All reported problems existed also before the release of MapX v5.

### Problem: MapX doesn't load from any url
- Concerned OS: Mac OS High Sierra Version 10.13.5
-  ERROR reported: webgl=false
- Concerned browsers: Chrome Version 67.0.3396.99 - Firefox version 44.0.2 - (OK SAFARI).
- Graphic accelleration in Chrome is active.

### Problem: MapX load from app.mapx.org but not as i-frame in unbiodiversitylab.org
- Concerned OS: MAC OS Sierra Version 10.12.6 
- No error reported  
- Concerned browsers: only Chrome Version 67.0.3396.99

**Comment by fxi** [comment]
I close this, reason given by email.

In depth : 
- Webgl is really well supported (99% percent of desktops) : https://caniuse.com/#search=webgl 
- If the user disable webgl, he or she will not be able to use MapX.
- Others errors seems to be linked to a add-ons or plugins that does block MapX.

Tips : disable plugins (addBlock, https everywhere, zotero, last pass) : MapX can be blocked without any reason.

**Comment by antobenve** [comment]
Extensions were disabled while performing the tests, so they shouldn't have a role in provoking the failures.According to you there is no reason for investigating on the mapx side the reasons why this is happening in any case. Am I right? -------- Original Message --------Subject: Re: [fxi/map-x-mgl] MapX doesn't load properly on Mac: info on problem (#283)From: "F.Moser" To: fxi/map-x-mgl CC: antobenve ,Author I close this, reason given by email.
In depth :

Webgl is really well supported (99% percent of desktops) : https://caniuse.com/#search=webgl
If the user disable webgl, he or she will not be able to use MapX.
Others errors seems to be linked to a add-ons or plugins that does block MapX.

Tips : disable plugins (addBlock, https everywhere, zotero, last pass) : MapX can be blocked without any reason.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fxi/map-x-mgl","title":"fxi/map-x-mgl","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/fxi/map-x-mgl"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fxi in #283: I close this, reason given by email.\r\n\r\nIn depth : \r\n- Webgl is really well supported (99% percent of desktops) : https://caniuse.com/#search=webgl \r\n- If the user disable webgl, he or she will not be able to use MapX.\r\n- Others errors seems to be linked to a add-ons or plugins that does block MapX.\r\n\r\nTips : disable plugins (addBlock, https everywhere, zotero, last pass) : MapX can be blocked without any reason.\r\n\r\n\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/fxi/map-x-mgl/issues/283#issuecomment-412526431"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/fxi/map-x-mgl/issues/283#issuecomment-412526431",
"url": "https://github.com/fxi/map-x-mgl/issues/283#issuecomment-412526431",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [fxi/map-x-mgl] MapX doesn't load properly on Mac: info on problem (#283)",
"sections": [
{
"text": "",
"activityTitle": "**F.Moser**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@fxi",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"fxi/map-x-mgl\",\n\"issueId\": 283,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/fxi/map-x-mgl/issues/283#issuecomment-412526431"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 367660644\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by antobenve** [comment]
I am going to explain you better:
- Several people performed the test on app.mapx.org. They confirmed the same results on v4.app.mapx.org and that they had the same problems before July.
- Two of them reported problems at loading app,mapx.org on Chrome (Version 67.0.3396.99) and Firefox (Version 44.0.2 - not recent).
- One person reported failure at loading a MapX i-frame in unbiodiversitylab.org using Chrome (Version 67.0.3396.99). Other browsers behave properly.  The same person loads MapX properly outside unbiodiversitylab.org with Chrome too.

I am asking to update Firefox to the person who is using the old version so that we can see whether only Chrome is concerned.
