### ISSUE TITLE
Views in panel not loaded on Firefox

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#292]
### Problem:
**The list of views in the panel is not loaded when MapX is loaded on Firefox.** 

_Info:_
- It happens when loading MapX directly with a url (non-logged users go to "World", logged users go to their old project, specific links to views, collections etc loads MapX on a specific project....)
- It doesn't happen when selecting a project from the dropdown list in MapX.

_OS where it has been tested:_
- Windows 7
- Mac OS High Sierra

_Version of browser:_
Firefox 61.0.2

**Console:**
`Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.`

**Results of test on browser compatibility:**
```
browser=true
array=true
function=true
object=true
json=true
worker=true
uint8ClampedArray=true
arrayBuffer=true
webgl=true
websocket=
    open=true
    close=true
    message=true
    send=true
    error=none
```

**Comment by fxi** [comment]
In both app and test.app.mapx  ?

**Comment by antobenve** [comment]
Windows 7: only on test.app.mapx.org
Mac OS High Sierra: I presume app.mapx.org (waiting for feedback)

**Comment by antobenve** [comment]
I have the problem on app.mapx.org as well but it is not systematic (before I hadn't, now yes). The error in console is the same to the one I reported.

**Comment by antobenve** [comment]
Update: On Mac OS High Sierra the consequences of the error I reported are larger:
app.mapx.org --> views don't load in panel
test.app.mapx.org --> MapX don't load at all (white page)

The reported error is the same.

**Comment by fxi** [comment]
This could be linked to a stuck service worker:
1. Remove cache for app.mapx.org and test.app.mapx.org
2. Remove application data. E.g. in Chrome : developper tools > application > clear storage > clear site data
3. In your browser javascript console, type  `mx.helpers.removeServiceWorker()`
@antobenve You can maybe create a small step-by-step guide in the wiki, it could happen until the service workers things is fully mastered...

Reopen if needed.
