### ISSUE TITLE
Secondary variables are removed from a view after edits were made using QGIS

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#293]
Secondary variables are removed from a view after its source was edited in QGIS using the temporary access to the database (in the toolbox).

It's problematic for the dashboards using the "click on features" option to fetch data.

#### More details
In mx_views -> data, the key "names" is replaced by the source attribute. It should be an array containing the secondary attributes.

#### Before edition
``` JSON
 "names": [
            "min_status",
            "min_nap",
            "min_ratification",
            "min_nap_implementing_agency",
            "ghg_asgm_hg_mean",
            "ghg_year",
            "pop_number",
            "usgs_au_production_2014_estimation",
            "asm_number_of_mining_sites",
            "adm0_name"
        ]
```
#### After edition
``` JSON
 "names": "min_status"
```

**Comment by fxi** [comment]
It should be solved by f2e6446. Reopen if needed.
