### ISSUE TITLE
Test version: The active view in panel freezes when editings are saved.

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#294]
When a view is edited from its configuration window and the editings are saved the view in the panel seems active (button is bold) but it is not:
- no abstract,
- no legend,
- no views' buttons,
- no data shown on map.

The problem is solved once the view's button is clicked twice and the view is re-activated.
![image](https://user-images.githubusercontent.com/30286565/44350656-37a3bb80-a4a0-11e8-9a6a-8c254b85567c.png)

OS: Windows 7
Browser: Chrome
MapX version: test.app.mapx.org

**Comment by antobenve** [comment]
@fxi there is still something to fix about edits of views and updates on screen:
- the title of the view is not updated on the panel when the view is edited. All the rest (abstract, legend, data on map) is.

**Comment by fxi** [comment]
Done, will be available in the next update. Reopen if needed.

**Comment by antobenve** [comment]
Thanks
