### ISSUE TITLE
Improve text related to the following error: Joining a project with an email that is already associated to that project

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#297]
When a public user tries to join a project with an email that is already associated to the project, the user receive an "Unexpected error" without further info. It would be better to have a text that explain that the user used an email that is already linked to the project he was trying to join.

**Comment by fxi** [comment]
How does a user join a project if he/she is already a member ?

**Comment by antobenve** [comment]
If you are not logged in you can ask to Join a public project. In this case an email is demanded. If you enter an email that is already used in the project you get the error.

**Comment by antobenve** [comment]
Maybe it is not something that will happen often but we never know.

**Comment by fxi** [comment]
Oh, yes, this will happen. 
<img width="500" alt="mx_membershiprequest_already_member" src="https://user-images.githubusercontent.com/1196833/44403173-071d5980-a554-11e8-8d2f-200b07c799b7.png">

This error was not detected in this context, but before during init and after, were it crashed. I've added this in the validation part.

**Comment by antobenve** [comment]
Thanks. Then I can close the issue. Very fast :)
