### ISSUE TITLE
Views become not-editable by anybody in this case:

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#298]
What I did is the following:
1) I created a view with an admin account and assigned editing rights to a specific member.
2) The member changed the editing rights to "blank" by removing him self from the list.

Result: both the creator and the only editor don't have the right to edit the view.

**Comment by fxi** [comment]
Ok.
The last user to save a view become the last editor and should therefore be able to edit the view, no mater what.
I was not able to reproduce your description, but I found a more awkward bug that could lead to some confusion, maybe something like you described.
Can you try to reproduce this issue on the test version ?
Thanks

**Comment by antobenve** [comment]
Let me try

**Comment by antobenve** [comment]
I still have the same problem. I could only try with raster views now as I can't upload a source currently due to the other bug. I'll see tomorrow again.

**Comment by antobenve** [comment]
This was solved by adding the last editor id to the editors column in mx_views
