### ISSUE TITLE
Views in specific project don't load 

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#305]
UN Environment POPs views are not shown on panel when the project is opened or refreshed

**Console**:
[app.mapx.org-1534954142903.log](https://github.com/fxi/map-x-mgl/files/2311128/app.mapx.org-1534954142903.log)

**Comment by antobenve** [comment]
Now the views of this project don't load in test version too.

**Comment by fxi** [comment]
Now It should be imposible to save a view that have no title or abstract, independently of the validation result of the editor.
