### ISSUE TITLE
Language in view and style form

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#31]
### Expected Behavior

Make clearer and intuitive in which language we are working in the view and style form.

### Current Behavior

Introduce the legend information in other language is not very intuitive. 

### Possible Solution

Introduce a bottom in the view and style form to change/switch the language. Or a label/tag that indicates the active language.

### Steps to Reproduce

1.Change language 
2. Fill view information 
3. Fill labels (style information)
4. Change again language to fill the information in other languages
...

**Comment by fxi** [comment]
Switching language during an edition could be tricky, as current language define which part of the view content is currently edited. Switching language could lead to unsaved information or information saved in the wrong language, as forms should be regenerated. And except for story maps, no backup is done.

I will think of a better way to handle this.

Thanks.

**Comment by alejandraarango** [comment]
Maybe just a label that indicates (not switch) in which language you are working in the view and style form can also be enough. This could prevent errors in the language in which you are entering the information. See image:
![language_label](https://user-images.githubusercontent.com/28750477/28280429-05cddf0c-6b24-11e7-914a-754ef005e8f6.png)

Another option could be that the form is in different languages as in the text metadata form.

<img width="625" alt="capture d ecran 2017-07-17 19 17 17" src="https://user-images.githubusercontent.com/28750477/28280634-b0dae796-6b24-11e7-901e-a4d285b0e91e.png">

**Comment by fxi** [comment]
I implemented a new way of editing view title and abstract : all titles are now editable, independently of the language of the interface.


![mx_language_view_edit](https://user-images.githubusercontent.com/1196833/28715606-0f8dd9c0-7399-11e7-848f-2f091b1a58eb.gif)
