### ISSUE TITLE
Widgets in dashboards are not displayed.

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#317]
I checked on several views and all dashboards seem desactivated (Iraq Marshlands and Minamata projects). 
If the dashboard button on top of the screen is clicked, an empty dashboard is displayed.

**Comment by antobenve** [comment]
I'm sorry, it is quite weird but I had the problem on app.mapx.org but not in test.app.mapx.org and afterwards I decided to try again on the app.mapx.org version and they work. I guess it was related to service workers as I'm with my laptop and I hadn't used it for work in a while.

**Comment by fxi** [comment]
I can't reproduce it. 

And please.. As a collaborator, you should be able to add a copy of the important part of your console logs. I don't ask you a huge investigation, just the minimum. See how Scott do it, e.g. #311

**Comment by antobenve** [comment]
Sorry @fxi, I couldn't get the console log because the problem didn't occur a second time. I immediately closed the issue in fact.
