### ISSUE TITLE
Bug display legend in different languages 

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#32]
### Current Behavior

Once the language is changed, the title and abstract change the language, but the labels (style view) do not change. Turn off view and turn on to display the legend correctly.

### Steps to Reproduce

1. Go to Peru
2. Turn on view “2016 Mining Unites” 
3. Change language to Spanish
4. The labels don’t change the language. See image
<img width="1280" alt="capture d ecran 2017-07-13 10 46 45" src="https://user-images.githubusercontent.com/28750477/28158964-baecf326-67bb-11e7-913b-d65c5f1bbaf9.png">
5. Turn off the view 
6. Turn on the view
7. Now the legend is correctly display

**Comment by fxi** [comment]
This has been solved.

Please close if it's ok or comment for further changes.

Thanks.
