### ISSUE TITLE
Point style: Reorganised data

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#33]
### Expected Behavior

Send biggest circles to the back and bring to the front the smaller circles. 

### Current Behavior

Using proportional circles - the biggest circles are in front, covering the other circles. See image: 

<img width="1268" alt="capture d ecran 2017-07-17 19 25 22" src="https://user-images.githubusercontent.com/28750477/28280947-bcec9ee8-6b25-11e7-93b9-dadcb31fa90a.png">

**Comment by fxi** [comment]
The current behaviour is this one : the last rules is processed to be the last on the "stack". Which means it will be in front. I've reversed the rules.

Is that better ?

![mx_circle_position](https://user-images.githubusercontent.com/1196833/28712049-e84ce860-7389-11e7-91e2-45e5b5d014f6.gif)
