### ISSUE TITLE
Loading views stall sometimes

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#337]
When opening a project the loading of the views sometimes don't progress to the end and gets stuck.
The charging circle that testifies that views are being loaded blocks and no view is displayed.
This is the console:
[test.app.mapx.org-1539088818322.log](https://github.com/fxi/map-x-mgl/files/2460396/test.app.mapx.org-1539088818322.log)

**Comment by fxi** [comment]
mmh, looks like "no space left on device" was the cause of this.
It should be solved now, please try it.

**Comment by antobenve** [comment]
If it happens again I will let you know here. Thanks.
