### ISSUE TITLE
Style: coding null value is not working

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#339]
In the missing values section, an empty value is treated as an empty string "" and not a NULL. 
Data having a NULL value in the db are not shown on the map. 

![image](https://user-images.githubusercontent.com/19908801/46674463-7d494e80-cbdc-11e8-99f6-d8977cb1578c.png)
![image](https://user-images.githubusercontent.com/19908801/46674637-f5177900-cbdc-11e8-833e-383b92de71ff.png)

**Comment by fxi** [comment]
We can't set a null value, it does not work in our editor. And string of length 0 is not null. 
However, I found a way to represent nulls as nodata.
Will be available in 1.5.23.

**Comment by thomaspiller** [comment]
I did some tests and the problem seems solved.
