### ISSUE TITLE
Access to reviewers: Create new bottom  “share” in each view

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#34]
### Expected Behavior

Give access to reviewers for some of the view layers. 

### Possible Solution

For each view, a "share" button would get a link containing the name of the view and the user's token. This link allows you to view only this view without having to identify yourself.

**Comment by fxi** [comment]
done.
![mx_share_link](https://user-images.githubusercontent.com/1196833/28715397-052c134e-7398-11e7-85e1-2bc2074e7303.gif)

**Comment by nicolasray** [comment]
Would that be possible that the view be already switched on when one arrives on it through the shared link?

**Comment by fxi** [comment]
Yes, this is possible.

As "views" query parameter accepts multiple views, the "open" parameter will open every views set.

i.e.  `?views=a,b,c&country=AFG&open=1` will automatically open a,b and c in Afghanistan.

Is that ok ? 

If yes, please set a priority and remove "fixed" label.

**Comment by nicolasray** [comment]
Yes, let's do it as you suggest, as View links should anyway point to only one view at the moment.
