### ISSUE TITLE
Potential webworkers problem - Failed requests are not removed from cache (token problem for Mapbox raster views)

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#348]
Failed requests for tiles are stored in cache. 
As a result, the view can't be accessed and an error 401 is thrown although the tiles should be available (the token was updated).
Removing the cache manually solved the problem.

**Comment by antobenve** [comment]
I'm closing the issue because the problem was not clearly understood. If the problem will occur again it will be investigated whether the failed request is coming from the webworker or the server directly. In the first case, the issue will be re-opened.

**Comment by antobenve** [comment]
@fxi , Florian and Saskia also experienced the problem.
Requests for tiles fail repeatedly for the view "here" until the cache is deleted. Refreshing the page doesn't solve the problem.

The failing requests were not coming from serviceworkers. Under "Network-->Size" the amount of downloaded data is however 0k.
See attached log.

[Antonio_log_network2.txt](https://github.com/fxi/map-x-mgl/files/2529261/Antonio_log_network2.txt)

Requests fail because they are featured with old "app_id" and "app_code" parameters that are not anymore valid. 
Is it related to taking cached requests and sending them to the server? Why isn't the request updated after it fails or in case we refresh the page?

Here the two requests:
Failing one (before emptying cache): https://1.aerial.maps.cit.api.here.com/maptile/2.1/basetile/newest/satellite.day/12/2129/1434/512/jpg?app_id=BQ9W6qK21snz3EGGmTpW&app_code=N6cdfEYvPKej8IvfdIMUcw&ppi=72

Succeeding one (after emptying the cache): 
https://1.aerial.maps.cit.api.here.com/maptile/2.1/basetile/newest/satellite.day/13/4254/2871/512/jpg?app_id=fGLfEdFmYwbEVQaO7DhX&app_code=bcOOdf_UD3-A18j_HXxmbw&ppi=72

Please reopen the issue in case you think something can be done on this.

**Comment by fxi** [comment]
mmh, I think I've found something. The map style could have been stuck in the indexedDB, as I've made an attempt to save it with localforage, before working with app cache and webworker.
In test.app.mapx.org, there is a version without this : we fetch it synchronously at the build time.

**Comment by antobenve** [comment]
Ok. If the problem doesn't occur on the test version then we should be good (if this is version you'll push into the other).
