### ISSUE TITLE
Manage external views - views' titles are not reloaded after clicking "Save"

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#349]
- In "Manage external views", when the "Save" button is clicked, the list is void.
Problems:
At this point the "Save" buttonis still active and, if clicked, all shared views to the project through this mechanism are un-shared.
Furthermore, if the empty field is clicked, the available views are displayed by ID.

Suggestion:
1) After clicking "Save" the list of available view is reloaded and titles are displayed again or 2) the "Save" button is grayed.

**Comment by thomaspiller** [comment]
Duplicate #366
