### ISSUE TITLE
Feature request: have a scale & a north arrow in MAP-X

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#35]
### Expected Behavior

A scale and a north arrow must be added to MAP-X on views, screenshots & prints.

**Comment by fxi** [comment]
Done. This will be available in the next update.
![mx_scale_north](https://user-images.githubusercontent.com/1196833/28710811-c0c7d4d4-7385-11e7-908a-1cef479b3b86.gif)
Will be available in the next update.
