### ISSUE TITLE
Typo in the metadata window

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#354]
In the "edit metadata" window, It's written _m**é**tadata_ instead of _m**e**tadata_ (in the English version).
**NB**: I can't suggest the change in the dictionary as this typo is not in the Json main dictionary 
![image](https://user-images.githubusercontent.com/25179050/48189348-459b0700-e340-11e8-8bf3-4117e807a01f.png)

**Comment by fxi** [comment]
The metadata editor has been rewritten. Labels has been updated:
![image](https://user-images.githubusercontent.com/1196833/48190022-db836180-e341-11e8-91f5-c61d66214f23.png)
And fyi, labels in integrity framework have been changed:

![image](https://user-images.githubusercontent.com/1196833/48190070-fbb32080-e341-11e8-8367-0ba31ba6d6d7.png)

**Comment by MarionPlanque** [comment]
Mant thanks for this; but this is the French version, is the accent deleted in the English version?

**Comment by fxi** [comment]
yes. 
![image](https://user-images.githubusercontent.com/1196833/48190930-3453f980-e344-11e8-8cf1-698d0d1f78d9.png)

**Comment by MarionPlanque** [comment]
Great, perfect! Many thanks
