### ISSUE TITLE
ContentTools does not load in v.1.5.26

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#356]
[test.app.mapx.org-1541670521469.log](https://github.com/fxi/map-x-mgl/files/2561183/test.app.mapx.org-1541670521469.log)

**Comment by fxi** [comment]
@antobenve Here is a cleaner version of your report:
Hi @fxi (optional),
In the current test version (1.5.26), the button to edit the content of a story map slide does not appear. The logs says 
`TypeError: Cannot set property DEFAULT_TOOLS of [object Module]`
The module is not loading.

**Comment by antobenve** [comment]
Close because corrected in next versions
