### ISSUE TITLE
Feature request: display in MAP-X the x,y coordinates of the cursor

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#36]
### Expected Behavior

Add a small "box" (maybe at the bottom of the screen) with the x,y coordinates of the cursor.
This "box" could be dynamic (as in QGIS) and could allow the user to enter coordinates to access a specific area in MAP-X.

**Comment by fxi** [comment]
done.

Available in the next update.

![image](https://user-images.githubusercontent.com/1196833/28707253-fd481710-7377-11e7-8a77-1ecd21fde523.png)
