### ISSUE TITLE
List of non-urgent glitches

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#366]
- [x] External views: when one removes the external views from the toolbox, they are not removed from the views panel. MapX has to be reloaded to make them disappear.

- [x] The filters in the left panel are not responsive to changes.

- [x] The full-screen button must be double-clicked to be activated.

- [x] The dashboard remains displayed when in immersive mode. Same if you mask the views panel. Is this the expected behavior?

APP: v.1.5.29
API: v.1.5.29
Windows 10 Pro 64-bit
Chrome: 70.0.3538.102 (Official Build) 64-bit
All add-ons disabled

**Comment by fxi** [comment]
Immersive mode remove buttons at top and left panel. Everything else remains. If this is not wanted, I can remove it also.

**Comment by antobenve** [comment]
###All browsers:
- [ ] External views: 1) After clicking "Save", the list of external views is empty. Clicking Save again will remove all external views [danger]. 2) If the field is clicked, the drop down list shows the ID. 
- [ ] PixOp: Highlight mode: The highlight of overlapping areas is not generated sometimes for point data no matter how long we wait (maybe related to the high amount of rows in the attribute table of point datasets).
- [ ] The WMS generator still doesn't work. The "Get layers" button seems to provoque the loading of a list of layers, however the dropdown list in Layers is empty and invisible (can be scrolled to be made visible in Firefox) 
![fig 1](https://user-images.githubusercontent.com/30286565/48704683-83791480-ebf7-11e8-91e3-51dccd969e85.JPG)

**Comment by antobenve** [comment]
Update v1.5.30:
- [ ] Edit source metadata: The pop-up window doesn't increase its size when the drop down list is displayed.
- [ ] Wrong version name in Toolbox (both should be 30):
	Version app server : 1.5.29
	Version app client : 1.5.30

**Comment by antobenve** [comment]
@fxi, You're right for point 1. Sorry. The issue only occurs if you previously try to re-shape the container manually.
