### ISSUE TITLE
View: edits are not saved in the database

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#368]
After editing the view, a click on the  "save" button doesn't save the edits in the database.
This issue is not generalized, it seems to be specific to this view.
No errors in the console.

View: MX-6HUA6-G352H-XOYE2
Project: Minamata Convention on Mercury

MapX v1.5.29 (online version)
Windows 10 Pro 64-bit
Chrome 70.0.3538.110 (Official Build) (64-bit)
No add-ons.

**Comment by fxi** [comment]
source without value ? No attributes or attributes with null only ?

**Comment by fxi** [comment]
Are you able to reproduce this on your local stack ?

**Comment by thomaspiller** [comment]
The problem is gone, I can save the view now.
