### ISSUE TITLE
OGR2OGR doesn't support .sql files dumped out through pg_dump

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#374]
Files in .sql format that were dumped out with the method pg_dump are not supported by ogr2ogr neither as .sql files, nor as .zip files. This generates the following error when uploading the files in MapX through the CURL request that Scott employs. 
Here a screenshot Scott sent me:

![image](https://user-images.githubusercontent.com/30286565/49737880-389a6c00-fc8e-11e8-9fef-4da83cb0a9ab.png)

It seems that files dumped out using pg_dump can only be restored into a database using psql (or pgadmin).

**Comment by fxi** [comment]
@antobenve  If logs are text, thanks to provide text version (searchable). 
And please avoid publishing private token : every person with the correct match "token" + "project" + "id" will be able to publish data into private project : not good.
So, no token, project or id...
What are the logs for the zipped version @scabecks ?

**Comment by antobenve** [comment]
@fxi Sorry for the token. I realized there was the token in clear 1 second after I posted it and I immediately removed it. Now I got the project and ID masked too. This is all I have and I hope it can help you in the meanwhile until Scott can publish his text log.

**Comment by fxi** [comment]
@antobenve  FYI, if somebody has subscribed to MapX issues – anyone can do it – he/she will receive the image you posted first, not edit. 

For the issue : the idea is to remove the ogr2ogr step completely in the import and pipe the sql content into postgres. But that's a major security issue, as we use pg_write to add data : anyone with write access to a project could do any write/delete/update operation in MapX. Which is not good. 

One possible workaround  – to test locally first, not in prod – 
- Upload a geopackage with a single feature and all attributes and types. Maybe no feature could also work.
- Use the temporary access to a source to add all the features. Using psql, R, QGIS, or whatever.

**Comment by scabecks** [comment]
Sorry for the slow reply guys. I was drinking too much eggnog (and in New Zealand). Happy new year by the way!

(I'm sure you've figured this all out by now but) pg dumps can only be read back into a database using psql (or pg_restore for some dump particular formats, non-plain-texts formats, but not the standard dumps). OGR cannot handle them.

**Comment by fxi** [comment]
@scabecks Happy new year ! 
Yep, I think @antobenve can close this now.

**Comment by antobenve** [comment]
Sure. The issue is now closed.
