### ISSUE TITLE
"Theme Configuration" naming is cut

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#375]
In the toolbox, the label of "Theme configuration" is cut and shows only "Theme config".

![2018-12-10_16-12-52](https://user-images.githubusercontent.com/25179050/49741684-3a1c6200-fc97-11e8-9fdb-6d3b99d01270.png)

**Comment by fxi** [comment]
```js
  {
    "id": "title_settings_colors",
    "en": "Theme configuration",
    "fr": "Configurateur de themes",
    "es": "Configurador de temas",
    "ru": "",
    "zh": "",
    "de": "",
    "bn": "",
    "fa": "",
    "ps": ""
  }
```

done
