### ISSUE TITLE
rev. 1.5.32 manual testing results

### ISSUE THREAD

**Issue by fxi** [fxi/map-x-mgl#376]
## Manual testing results
- [x] project creation
- [x] project configuration
- [x] invite new member
- [x] update roles
- [x] upload source form
- [x] upload source drag and drop
- [x] manage sources
- [x] add partial metadata
- [x] validate partial metadata
    - Issues : mismatch between "in depth" validation and flag.
- [x] view list: check partial metadata
- [x] update metadata – fill missing
- [x] view list: no warning flag after modification
- [x] DIAF star
- [x] vector view creation
- [x] share view from edit window
- [x] create style
- [x] download
- [x] printscreen
- [x] tests options (zoom to features, filters, sharing…)
- [ ] filters (bottom left panel).:
     - Not updated after view create
- [x] story map creation
- [x] custom code
- [x] dashboard
- [x] menu bar (zoom, pixop, reset orientation…)
- [x] add external view
- [x] SQL custom queries
- [x] remove external view
- [x] view, source, project removal

**Comment by antobenve** [comment]
### Mismatch between "In depth validation" and flagging in view's panel:
- When the "In depth validation" tool of the metadata of a source layer throws "Invalid keywords" only, the view associated to that source is not flagged.
.....The "Invalid keywords is given when a keyword field exists but it is empty.

**Comment by fxi** [comment]
So, an empty keyword is invalid, right ?

**Comment by thomaspiller** [comment]
rev. 1.5.32: SQL custom queries: if the tool is closed and reopened, the previous query is still present in the pop-up. I think it should be remove from the UI.
