### ISSUE TITLE
rev. 1.5.36 & 1.5.37 manual testing results

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#379]
## rev. 1.5.36

- [x] Deletion of an empty view -> disconnected from the server  ||  no logs

- [x] The source is not defined in the following conditions:
1. creation of a new project
2. upload of a new source layer
3. manage sources: enabling WMS for the new source -> in GeoServer both workspaces & data stores are created
4. creation of a new view with read access = public -> save -> pop-up Unexpected issue : mxPublishGeoServerView : source not defined  ||  no logs
5. creation of a new view with read access = members -> save -> pop-up Unexpected issue : mxUnublishGeoServerView : source not defined  ||  no logs

If the view is created before enabling WMS publication everything works fine.

## rev. 1.5.37

- [x] For some questions, the tooltip is partially hidden in the DIAF pop-up.
![image](https://user-images.githubusercontent.com/19908801/50344273-9fd7dc00-052a-11e9-81ca-1d135f8ec461.png)
- [x] In the header, the term "key" is not very user-friendly. You could replace it with "Questions"? Any other suggestions?
- [x] Download tool returns "The source can't be downloaded. The download is not allowed." even if it is enabled in _Manage sources_.
- [x] Data download can be activated from two places: the metadata form and _Manage sources_.

**Comment by fxi** [comment]
Not if projects are correctly isolated, I think.  A user may want to publish something on WMS from a private project : that's the user's choice. The user should be warned that everyone with the correct path to the wms endpoint will be able to see that data, though. @PierreLacroix ?

**Comment by PierreLacroix** [comment]
We should not restrict the publication. I agree with @fxi

**Comment by thomaspiller** [comment]
The last open comment is available in the issue #393.
