### ISSUE TITLE
The pop-up is not updated after changing the aliases

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#380]
The pop-up is not updated after a change in the value of the aliases in _Edit source metadata_.
I looked in the database and the value of the aliases is updated correctly.

MapX: online v1.5.35 & local v1.5.37
Chrome 71.0.3578.98
Windows 10
No add-ons

**Comment by fxi** [comment]
@MarionPlanque @thomaspiller 
Alias update was delivered through the metadata, validation, badge and public flag update. This was disabled for non-public view. I've changed this and it should be available in the next release.
