### ISSUE TITLE
Bug - Dropdown menus when managing sources 

### ISSUE THREAD

**Issue by tdearden** [fxi/map-x-mgl#387]
Chrome 71 on Windows 10:

The drop down menu associated with "Manage Sources" and "Edit Sources Metadata" in the toolbox does not extend past the border of the pop-up. Thus, the content is masked and the user can only see one option when scrolling.  The pop up only extends horizontally, not vertically. The options at the bottom get missed or are hard to find.

![bug with drop down 2](https://user-images.githubusercontent.com/41048297/51693211-cd6ae600-1ffe-11e9-8213-2dd391650487.gif)

**Comment by fxi** [comment]
Thanks !

Should be covered in rev's issues described in #393.
