### ISSUE TITLE
rev. 1.5.38 manual testing results - Blocking bugs

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#388]
All issues are reproducible on Chrome 71.0.3578.98 (64-bit) & Firefox 64.0.2 (64-bit) - Windows 10 Pro

[ @antobenve note: All non-blocking bugs have been reported in #389 . Other specific issues have been made on specific topics]
#### Invite new member & join project
- [x] [ @fxi note: linked to our provider ] Disconnected after clicking on the button: unexpected issue = mxSendMail : Server can't send email to < user email >

 [ @fxi edit: removed code-unrelated logs ]

#### Dashboard
- [x]  All widgets using Highcharts are not displayed.
```
Uncaught (in promise) Error: TypeError: hc.merge is not a function
Uncaught (in promise) Error: TypeError: this.modules.highcharts.chart is not a function
```
#### i button (metadata)
- [x] Disconnected after clicking on the button: unexpected issue = argument is not interpretable as logical

#### Download
- [x] Disconnected after clicking on the button. No unexpected issue pop-up. Console: The application exited unexpectedly. socket hang up

#### View configuration
- [ ] [ @fxi note : can't reproduce. Which view? ] Adding/removing a collection (new or existing) to a view can cause disconnection when saving.
[ @antobenve note: this was experienced in few cases on a new view in Chrome. Could not be reproduced systematically ]

#### Geoserver
[ @antobenve note: important new bug added at the end of paragraph ]

I have not managed to reproduce these problems consistently!
- [ ] After enabling WMS for a source, the workspaces are created but I sometimes get disconnected when I edit views especially after a "read access" change.
- [ ] Deleting a view or changing the "read access" : public to ... -> layer is not delete in the GeoServer

 [ @fxi note : lots of logs seems to be geoserver error not related to MapX.. ]
 [ @fxi edit : removed obviously unrelated logs, kept probably significant one ]

```
geoserver_1  | 25 Jan 14:36:49 INFO [rest.catalog] - DELETE layer 'MX-88R-NT5-YTD-PWU-M39@gs_ws_a:MX-OHYYC-3M0Z9-CMMZF'
geoserver_1  | 25 Jan 14:36:49 INFO [rest.catalog] - DELETE feature typeMX-88R-NT5-YTD-PWU-M39@gs_ws_a@pg,MX-OHYYC-3M0Z9-CMMZF
geoserver_1  | 25 Jan 14:36:49 WARN [catalog.impl] - Failed to load actual store for FeatureTypeInfoImpl[MX-OHYYC-3M0Z9-CMMZF]
pg_1         | 2019-01-25 14:36:49.706 UTC [859] ERROR:  relation ""public.gt_pk_metadata"" does not exist at character 15
pg_1         | 2019-01-25 14:36:49.706 UTC [859] STATEMENT:  SELECT * FROM ""public"".GT_PK_METADATA WHERE 1 = 0
geoserver_1  | 25 Jan 14:36:49 INFO [rest.catalog] - POST feature typeMX-88R-NT5-YTD-PWU-M39@gs_ws_a@pg,MX-OHYYC-3M0Z9-CMMZF
geoserver_1  | 25 Jan 14:36:49 INFO [gwc.layer] - Truncating default style for layer MX-88R-NT5-YTD-PWU-M39@gs_ws_a:MX-OHYYC-3M0Z9-CMMZF, as it changed from polygon to generic
geoserver_1  | 25 Jan 14:36:49 INFO [geoserver.gwc] - Saving GeoSeverTileLayer MX-88R-NT5-YTD-PWU-M39@gs_ws_a:MX-OHYYC-3M0Z9-CMMZF
geoserver_1  | 25 Jan 14:36:49 INFO [rest.catalog] - PUT layer MX-OHYYC-3M0Z9-CMMZF
geoserver_1  | 25 Jan 14:38:03 WARN [catalog.impl] - Failed to load actual store for FeatureTypeInfoImpl[MX-FZTQ8-1ODRG-70DM0]
geoserver_1  | 25 Jan 14:38:03 INFO [rest.catalog] - POST feature typeMX-88R-NT5-YTD-PWU-M39@gs_ws_a@pg,MX-FZTQ8-1ODRG-70DM0
geoserver_1  | 25 Jan 14:38:03 INFO [gwc.layer] - Truncating default style for layer MX-88R-NT5-YTD-PWU-M39@gs_ws_a:MX-FZTQ8-1ODRG-70DM0, as it changed from polygon to generic
geoserver_1  | 25 Jan 14:38:03 INFO [geoserver.gwc] - Saving GeoSeverTileLayer MX-88R-NT5-YTD-PWU-M39@gs_ws_a:MX-FZTQ8-1ODRG-70DM0
geoserver_1  | 25 Jan 14:38:03 INFO [rest.catalog] - PUT layer MX-FZTQ8-1ODRG-70DM0

```

- [ ] Both workspaces that are created for a project ("...a", "...b") have the same active services (WMS,WCS,WFS).

#### Manage sources
- [ ] ~[ @fxi note : can't reproduce. Likely related to geoserver config ] Clicking "Update", even if nothing is changed, cause disconnection. No unexpected issue pop-up.~
[ @antobenve note : it was related to missing column "services" in mx_sources. ]

**Comment by fxi** [comment]
Follow up in #393
