### ISSUE TITLE
Non-blocking bugs and improvements v.1.5.38

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#389]
#### Update Mapx
- [ ] [ @fxi note : can't reproduce. ]  Popup doesn't close after installation is completed. "Install" button grayed. "Close" is active.
[ @antobenve note: the problem could only be experienced once in Windows 10. Ubuntu 18.04 didn't show this bug ]

#### Project
- [x] Namibia still missing
- [x] project name doesn't update when the language is changed
- [ ]  [ @fxi note : can't reproduce. ]  "Save" must be clicked twice in the project configuration window
[ @antobenve note: the issue occurred on Firefox in Ubuntu 18.04 and on Chrome in Windows 10 to Antonio. Thomas didn't experience this problem in a systematic way. ]

#### Edit Metadata form
- [ ] DIAF: the translation of the input values is no longer present (e.g. dont_know)

#### Filters (bottom left panel)
- [ ] [ @fxi note : can't reproduce. ] Edited views are not counted in the filter until the project is refreshed
[ @antobenve note: The problem is systematic. It can be reproduced in Chrome and Firefox. 1) Check the number of "Layers" in Filter. 2) Open the configuration window of any type of view in any project, 3) click "Save" and 4) check the number of "Layers" in Filter. It will be 1 less. 5) Refresh the page: it will be 1 more.

#### Drop down lists 
- [ ] [ @fxi note : can't reproduce. ] the window does not resize in Firefox -> scrollbars to navigate the list 
![image](https://user-images.githubusercontent.com/30286565/51901172-54c9a800-23b7-11e9-982b-914df7e2c4cd.png)

- [ ] [ @fxi note : can't reproduce. ] Antonio still has problems in Chrome (experienced with language drop down list). Window doesn't resize.
[ @antobenve note: the problem was only reproduced in Chrome on Windows 10. Chromium in Ubuntu 18.04 didn't show this bug. ]

#### Story map editor
- [ ] The map disappeared just once
```WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost```
[ @antobenve note: If anyone experience this bug again please report it here. ]

**Comment by antobenve** [comment]
### List of non-blocking bugs that are still found since previous versions:

#### DIAF star
- [ ] text as mouse hovers the star doesn't display in new language until the page is refreshed after the language is changed
 https://github.com/fxi/map-x-mgl/issues/379#issuecomment-451933257

#### Views and projects titles 
- [ ] allows special characters (-â etc... in project titles and views titles when the project and the views are created. Currently, special characters are only allowed when the titles are edited.
https://github.com/fxi/map-x-mgl/issues/299#issue-352535571

**Comment by fxi** [comment]
>  [ @fxi note : can't reproduce. ] Edited views are not counted in the filter until the project is refreshed
>[ @antobenve note: The problem is systematic. It can be reproduced in Chrome and Firefox. 1) Check the number of "Layers" in Filter. 2) Open the configuration window of any type of view in any project, 3) click "Save" and 4) check the number of "Layers" in Filter. It will be 1 less. 5) Refresh the page: it will be 1 more.

Yep, it was not clear. It's not the whole count system that's not correct, but only the count of layers.
Collections, theme, all other count seems correct. 
So, I got it now.

**Comment by fxi** [comment]
follow up in #393
