### ISSUE TITLE
[ popup ] Issue: Impossible to visualize data for more than 1 polygon if 2 or more polygons are overposed in the map.

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#39]
![polygon data in pop-up window](https://user-images.githubusercontent.com/30286565/28359946-32546f18-6c74-11e7-91ab-78730fdca35a.PNG)

### Expected Behavior
Selecting a point on map where 2 polygons are located should result in both polygons' data being visualized on the pop-up windows.

### Current Behavior
Only one polygon's data is shown. Smaller polygons that are totally recovered by others are impossible to be queried.

### Possible Solution
This works for point data. I guess the same solution might apply to polygons as well. 

### Steps to Reproduce

1. Select the view of a polygon data (Mineralized Areas 2011 for example)
2. Go towards the center of AFG and try to select the blue polygon inside the purple one 
3.
...

**Comment by fxi** [comment]
Thanks, very clear report.
I can reproduce this.
I've made a brand new popup function, with better filter handling.
This will be available in the next update.
