### ISSUE TITLE
Add a overlap tool button on map next to the PixOp button.

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#390]
#### Overlap tool
- [ ] Add a button in the menu bar next to pixop in order to access the Overlap utilities.

**Comment by fxi** [comment]
I'm sorry, I can't do it without a lot of work.

All source related tools must be grouped in one section to avoid a non-unified UI creation server side.
All source related tools are linked to a specific role. Having a button outside would break the logic.

So, I close this for now.
