### ISSUE TITLE
Alias minimum size is not checked in project configuration

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#394]
When specifying an alias for a project, the minimum size of 5 characters is not checked in the form.
Therefore, the "Save" button is not grayed out if you type less than five characters in the input.
#### To Do
- [x] Add minimum size validation
___
MapX 1.5.38 (local)
Chrome 71.0.3578.98 & Firefox 64.0.2
Windows 10
No add-ons

**Comment by fxi** [comment]
So validation was done, but not shown : the implicite behaviours was to ignore string from 0 to 4 characters.
I've pushed a new image with server side string validation done after 4 character.
So a message will be shown from 1 to 30 characters if anything wrong.

**Comment by thomaspiller** [comment]
This issue is solved (tested on local version 1.5.38).
