### ISSUE TITLE
Filter views by tag - size not dynamic.

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#397]
Hi @fxi , in the local version 1.5.38, the "filter views by tag" element assumes a fixed height if one of the option to filer is clicked.
This results in large part of the panel being covered and white space being displayed in the filter element in cases.
![image](https://user-images.githubusercontent.com/30286565/52343459-6f83c880-2a18-11e9-82a4-3a554b10fe6d.png)

Suggestion: Resize the element dynamically according to the number of tags like in the online version (v.1.5.35)

Tested on Ubuntu 18.04, Firefox (65.0 (64-bit)) and Chromium (71.0.3578.98 (Official Build)).

**Comment by fxi** [comment]
Is that still an issue in prod ?

**Comment by antobenve** [comment]
No, it is not. So I close this issue. Thanks
