### ISSUE TITLE
Issue: Difficult to visualize data in pop-up windows when more objects are selected

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#40]
![points data in pop-up window](https://user-images.githubusercontent.com/30286565/28359860-ed323e74-6c73-11e7-8e7b-3fa64bd23fe7.PNG)

### Expected Behavior
The data relative to each point or other kind of data that is selected on map when overposed should be separated by some space or thicker lines. It is not straightforward understanding how many objects were selected. It would also be extremely cool if while moving the pointer above the pop-up window the point to which that particular line is associated change color (to identify which point is that particular line of data associated to).

### Current Behavior
when 2 points are clicked their data is shown on the pop-up windows without any space of limit between the lines of data relative to each point. This behavior makes difficult spotting which data is associated to which point and understanding how many points were selected.

### Steps to Reproduce

1. Select a view with point data (Size of mineral deposits (USGS 2006 - National) for example)
2. Select where more points are present
3.Look at the pop-up windows results
...

**Comment by fxi** [comment]
Close this, continue in #39 
Thanks
