### ISSUE TITLE
Issue: Selection on data remain active when a view is unselected and selected again

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#41]
### Expected Behavior
When a view is selected for showing on map, the entire set of data should be visualized

### Current Behavior
Only a selection of data is visualized if a view is selected after a selection of data was applied through the pop-up window. The issue is that the selection remains active even after unselecting the view and reselecting it afterward. This might be an issue if people select a view and do not remember that they previously selected data through the pop-up window.

### Possible Solution
Reload the view entirely every time a view is selected

### Steps to Reproduce

1. Select a view which has secondary variables being shown in the pop-up window
2. Select one value from a secondary variable and show the data that have this value
3. Unselect the view
4. Select again that view
...

**Comment by fxi** [comment]
This should be solved by the new popup filtering thing.
I close this one and make a ref from #39
