### ISSUE TITLE
Feature request: Change Source and Sources titles in the metadata form

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#47]
### Current Behavior

The titles are not so clear. Could be clearer and standardises if the names are changed for those used in the Geonetwork. 

### Possible Solution

In the metadata forms change the name of: 
“Source” to “Distribution information”
“Sources” to “OnLine resources”

Eventually create a new field call, “Organisation name”. Sometimes the distributor is not the same organisation that created the data.

**Comment by fxi** [comment]
You can fork the project and modify this file:

https://github.com/fxi/map-x-mgl/blob/master/web/data/dictionaries/dict_schema_source.csv

Then make a pull request. Ask Google or Thomas if needed.

You can also contribute and fill the Spanish (es) section ;)

**Comment by alejandraarango** [comment]
I already changed the titles proposed and all the from is translated into Spanish.

**Comment by fxi** [comment]
Great. 
Where did you made the changes ?

**Comment by fxi** [comment]
ok.  I see .. You pushed directly in the repo. I've send you a email.

**Comment by alejandraarango** [comment]
Salut,

J'ai vu le mail que je tu m'a envoyée mais je peux pas te répondre depuis
le mail de la université.

J'ai croyais que le script que j'ai change c’était le frok mais no :(.
J’espère que tu peux garde les modifications. Sinon je peux le refaire.

Bonne journée,
Alejandra

2017-08-02 18:35 GMT+02:00 F.Moser <notifications@github.com>:
