### ISSUE TITLE
Issue: nothing appears in the left panel when a new source is dropped in MAP-X

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#50]
This issue concerns the new version -> https://mapx-dev.unepgrid.ch/app/test/

### Expected Behavior

When dragged and dropped in MAP-X, a new source should appear in the left panel.

### Current Behavior

When dragged and dropped in MAP-X, nothing appears in the left panel. We must move to another country and then go back to the one where the file was dropped to see the new source.

### Steps to Reproduce

1. Add a new source (in my case a GeoJSON)
2. Nothing appears in the left panel
3. Move to another country
4. Go back to the country where you dropped the file
5. The new source is displayed in the left panel

**Comment by thomaspiller** [comment]
I don't know if you have already worked on this issue but it seems to me that it only concerns the global data (dropped in World).

**Comment by fxi** [comment]
I can't reproduce this.
Maybe I've fixed this in the meantime.
I've seen a bug in the awk command to get the features length, maybe this is linked.

**Comment by thomaspiller** [comment]
I will show you a live exemple this afternoon. I think the issue is related to country with zero views.

**Comment by thomaspiller** [comment]
The problem has changed a bit. If you add a view in a country that doesn't have any, the view appears as it should. But if you pass from a country which has views to a country which hasn't, the views of the first country appear in the second (ie move from Afghanistan to Burkina Faso).

**Comment by fxi** [comment]
That's not good. I will fix this. 

Thanks.

**Comment by antobenve** [comment]
I think this problem is not relevant anymore. Can you confirm @thomaspiller ?

**Comment by thomaspiller** [comment]
You're right this issue is not relevant anymore.
