### ISSUE TITLE
Issue: failed to upload a zipped shapefile in MAP-X

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#51]
This issue concerns the new version -> https://mapx-dev.unepgrid.ch/app/test/

### Expected Behavior
The new source should be added to MAP-X db without trouble.

### Current Behavior
I dropped a zipped shapefile (9 MB zipped, 40 MB uncompressed) in MAP-X and then pressed the upload button. The upload & md5 calculation were very slow (more than 5 minutes). Then it was written on the screen "Loading schema..." and after a while, I got disconnected from the server.

I tried a second time and I had exactly the same issues.

Here's the link for the file:
https://www.dropbox.com/s/rm3aezzhuxilvcx/minamata_status_nap_mia_2017_07_31_GAUL_simplified_single.zip?dl=0

**Comment by fxi** [comment]
The output file is reported as a non-valid geojson but it passed the validation. 

But.. Using the new uploader in the toolbox, the layer is uploaded and displayed without problem.

![image](https://user-images.githubusercontent.com/1196833/28924180-13c3ddce-7861-11e7-8594-2c57e031e019.png)
