### ISSUE TITLE
Issue (?): labels are in bold character

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#52]
This issue concerns the test version.

### Expected Behavior
In previous versions, labels were in normal character.

### Current Behavior
In the legend, labels are in bold character.

![image](https://user-images.githubusercontent.com/19908801/28915414-5ceb55f8-783f-11e7-9eee-701e8fbfcd8c.png)

**Comment by fxi** [comment]
Fixed. Default label font weight from bootstrap.
