### ISSUE TITLE
Issue: text panels are partially off-screen for new views

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#53]
This issue concerns the test version.

### Expected Behavior
The text is supposed to be displayed in full.

### Current Behavior

After creating a new view,  when the cursor hovers over the buttons, the text panels are partially off-screen.

![1](https://user-images.githubusercontent.com/19908801/28916751-93621604-7843-11e7-9105-0d2d068df58f.png)
![2](https://user-images.githubusercontent.com/19908801/28916753-9575f730-7843-11e7-9cae-8a55f4d3c1d3.png)

**Comment by fxi** [comment]
done.
