### ISSUE TITLE
Bug point layer: The biggest value not appear

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#54]
### Current Behavior

The biggest values of the “Concentration of copper in sediments” and “Concentration of lead in sediments” are not displayed. 

Biggest values:

Copper: 201542.001049
Lead: 353.010774

**Comment by fxi** [comment]
on app/test ? Could you check again ?

![image](https://user-images.githubusercontent.com/1196833/28931798-87bdfdde-7877-11e7-8181-e32a545a94f3.png)
