### ISSUE TITLE
Information on source variable's value is given twice when clicking on a polygon on the map.

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#55]
### Expected Behavior
When a view is defined, if I only select one source variable and leave empty the case for second source variable, I should get information on the value of the source variable only once. 

### Current Behavior
When clicking on a polygon on map I get two times the same information and it is not nice.
This does not happen everywhere. But it happens with the view Land Cover Map over Mes Aynak (FAO - 2010) at least.

### Steps to Reproduce
1. Select this view.
2. Click on a polygon
3. Check other views where only one source variable was defined such as Terrestrial Ecoregions (WWF). For example the problem does not occur here.
![double variable for a view](https://user-images.githubusercontent.com/30286565/28962224-44db88e0-7905-11e7-8168-e11d8f8862ee.PNG)

...

**Comment by fxi** [comment]
Did you try /app/test ?

For now, available there, until I come back from vacation: https://mapx-dev.unepgrid.ch/app/test/

Lot of new stuff.

Check it out and close all your issues that have been fixed there. Or not.

And open new ones with the new bugs :)

**Comment by antobenve** [comment]
It was actually fine in the new version. Sorry
