### ISSUE TITLE
Malfunctioning of the selection process of specific legend's values.

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#56]
### Expected Behavior
If I select a specific value I expect seeing this and only this on map. I believe this is the aimed behavior.

### Current Behavior
All values above that number are shown on map. So, it only works properly when selecting the uppermost value.

### Steps to Reproduce
1. Select a view that contains numeric values.
2. Select a particular value from legend
3. Check map
...

### Detailed Description
It's possible that this could be solved by changing the type of style (continuous vs interval) but I don't fully see the difference between Interval and Continuous types of styling. May this be the reason of the problem?

**Comment by fxi** [comment]
This was a choice.

For make it more clear, I've put a >= and = sign before the legend input:
![image](https://user-images.githubusercontent.com/1196833/28965756-fcfda0b8-7912-11e7-83a0-24a976073364.png)

However, I can filter feature using the same class used in styles rules.

For example:
Click on 
-0 filter value from 0 to 4.99..
-5 filter value from 5 to 9.99..
-10 filter value from 10 to 29.99..
-30 filter value from 30 to max.

What do you think ?

For the continuous vs interval, this option does not exists any more.

**Comment by nicolasray** [comment]
Yes, I would like to have the filter working as you suggest at the end of your post ("I can filter feature using the same class used in styles rules"), because:
- it's the behaviour most users will expect by default
- it is possible to select values between, say, 30 and 45 (by clicking on values 30, 35, and 40).

**Comment by antobenve** [comment]
I also prefer the last option and I expected it to be this way in the beginning.
If I can suggest more as an user, I expected legend to show intervals when numbers are concerned. For example:
0-5
5.1-10
10.1-20
etc...
I know it may be ugly that ".1" but it removes all uncertainty.
If there is a better way please do as you wish.
Otherwise you

**Comment by antobenve** [comment]
I re-launch this issue as the way the filter works was not changed after Nicolas suggestions.
