### ISSUE TITLE
Colors should appear on map as they appear on legend

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#57]
### Expected Behavior
If opacity is set to a particular value the color changes in map. Consequently it should change in legend box as well accordingly.

### Current Behavior
Colors on legend box are 1.0 opacity. There is difference when looking at map and legend style. It may create problems when many values are present and very similar colors must be set in order to differentiate values.

### Steps to Reproduce
1. 
2.
3.
...

**Comment by fxi** [comment]
Check this on /app/test, I pushed an update just now.
Don't forget to follow up your issues : close them when fixed.

**Comment by antobenve** [comment]
It's fine. It works.
