### ISSUE TITLE
Issue: Views sidebox does not always update after having searched for a specific view

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#58]
### Expected Behavior
After having searched for a view, when deleting all text in the search windows all views must appear again in the views' sidebox and search box should be available for a new search.

### Current Behavior
Sometimes, quite often, the views' sidebox is not updated after the text in the search box is deleted. If I don't add any text, the same views as those that resulted from the previous search appear. If I start another search, it will search among the results of the previous search

### Steps to Reproduce
1. Make a search
2. Select a view
3. Maybe do something and/or wait for sometime
4. Delete text in the search box
5. Check whether views are again visible. If not, try another search.

### Detailed Description
When I try to reproduce this issue I don't succeed. I think it is a matter of doing something to a view after a search.....

**Comment by fxi** [comment]
Thanks.
I'm able to reproduce this each time.

1. Filter view list
2. Update a view
3. The list stay filtered
