### ISSUE TITLE
Issue opacity change with zoom on map (and doubling of points at specific zooms)

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#59]
### Expected Behavior
Opacity is set to a value and I expect it to be remain constant when surfing on the map

### Current Behavior
Points change their opacity when zoom changes. Furthermore, some points of some views (not all views behave the same) get double (two points closely spaced at the place of 1 point) at a certain zoom and at further more zoom they get back to their normal shape (1 point) 

### Steps to Reproduce
1. Select Concentration of cobalt in soils (Congo)
2. Zoom a lot and check each point changing opacity
3. Try with other views to check points doubling after a relevant zoom
![issue opacity zoom_1](https://user-images.githubusercontent.com/30286565/29132692-5c7d40ee-7d31-11e7-8306-36b9ad8c0a40.JPG)
![issue opacity zoom_2](https://user-images.githubusercontent.com/30286565/29132690-5c7b14fe-7d31-11e7-9c6b-637518376e5c.JPG)
![issue opacity zoom_3](https://user-images.githubusercontent.com/30286565/29132694-5c804b40-7d31-11e7-8bc4-5056782fc29a.JPG)
![issue opacity zoom_4](https://user-images.githubusercontent.com/30286565/29132691-5c7ba7d4-7d31-11e7-88b8-9135e0899d4a.JPG)
![issue opacity zoom_5](https://user-images.githubusercontent.com/30286565/29132693-5c7d6c40-7d31-11e7-923d-38408950b9da.JPG)
![issue opacity zoom_6](https://user-images.githubusercontent.com/30286565/29132695-5c833aee-7d31-11e7-94d2-763e14e67331.JPG)

...

**Comment by alejandraarango** [comment]
Double point video:

<img width="424" alt="capture d ecran 2017-08-09 18 51 16" src="https://user-images.githubusercontent.com/28750477/29133473-e20fe278-7d33-11e7-94df-da3812c3ced4.png">
<img width="291" alt="capture d ecran 2017-08-09 18 51 30" src="https://user-images.githubusercontent.com/28750477/29133478-e56cf4ba-7d33-11e7-9e61-384ed418a570.png">
<img width="505" alt="capture d ecran 2017-08-09 18 51 57" src="https://user-images.githubusercontent.com/28750477/29133481-e8f72902-7d33-11e7-9ae0-d71e8eb9d2a2.png">

**Comment by antobenve** [comment]
This issue is still present and express it self not only with opacity involontary changes (figs 1-2) but also with doubling of features displayed on map (Fig. 3-4). As you see the way the data is reported on map is strongly variable and depends on the zoom. 
I believe the changes in opacity might be related to the doubling of objects on map (figs. 3-4). When an object is doubled 2 objects are shown exactly on the same position, thus its opacity seems higher. To be investigated the way the visualization of objects on map changes with zoom. 

![doubling of points with zoom_change opacity_1](https://user-images.githubusercontent.com/30286565/33548745-812281da-d8e8-11e7-8191-e438d509f15c.JPG)
![doubling of points with zoom_change opacity_2](https://user-images.githubusercontent.com/30286565/33548748-82ab160c-d8e8-11e7-8bb7-6bd776c5fb50.JPG)
![doubling of points with zoom_1](https://user-images.githubusercontent.com/30286565/33548750-842a91e2-d8e8-11e7-9227-466b4fb81061.JPG)
![doubling of points with zoom_2](https://user-images.githubusercontent.com/30286565/33548751-852c5102-d8e8-11e7-8f48-028b8deb308c.JPG)

**Comment by antobenve** [comment]
I don't know if this was related to MapX or simply a Mapbox issue but now it seems to be OK. Therefore I close the issue.
