### ISSUE TITLE
Feature request: Change layer's level when more layers are visualized together

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#62]
### Expected Behavior
When selecting two layers, among which one of the two is polygons and the other is points, the points should be on a higher level than the polygons in order to be visible. There should be a way to define the layers position.

### Current Behavior
The position of layers is only based on the last editing date of a view.

### Steps to Reproduce

1. Select a polygon view and a point view and try to investigate point features. If you have the chance that the point view is higher up in the list you can analyse data. Otherwise they will be obscured by the other layer
2.
3.
...

**Comment by fxi** [comment]
You can move the layer. 
![mx_layer_position](https://user-images.githubusercontent.com/1196833/29765563-fb9c0c56-8bdb-11e7-92e7-fded8f972bc0.gif)
If it's ok, please close your issues.

**Comment by antobenve** [comment]
Ah, thanks. I didn't know it.
