### ISSUE TITLE
Issue: WMS external layering does not work through predefined servers

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#63]
### Current Behavior
Layers are not loaded if a predefined WMS server is selected. 

### Steps to Reproduce

1. Create a view
2. Configure it by selecting WMS configurator
3. Select a predefined server and try to upload layers available.
![issue wms layers](https://user-images.githubusercontent.com/30286565/29324101-44919bea-81e3-11e7-831f-a080c29f15bd.JPG)

...

**Comment by fxi** [comment]
Arf.. A dependencies was not up to date. Worked locally, but not on the remote.. Tried everything, recoded the thing. Updated the xml library, everything seems to be ok now. 
Should work, see #68

**Comment by antobenve** [comment]
It seems it works, although it still presents this issue when using the WMS configurator with columbia university when loading layers. It is weird because the server actually works if I manually enter this lines:

https://sedac.ciesin.columbia.edu/geoserver/wms?bbox={bbox-epsg-3857}&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&style=&layer=gpw-v4:gpw-v4-population-count-adjusted-to-2015-unwpp-country-totals_2020&format=image/png&transparent=true&height=256&width=256

https://sedac.ciesin.columbia.edu/geoserver/wms?service=WMS&version=1.1.1&styles=&request=GetLegendGraphic&layer=gpw-v4:gpw-v4-population-count-adjusted-to-2015-unwpp-country-totals_2020&format=image/png&transparent=true

![still issue wms layers after correction](https://user-images.githubusercontent.com/30286565/29884551-2c24d734-8db4-11e7-8696-aafe0fb7e017.JPG)
