### ISSUE TITLE
Issue: the location of the slides in the Afghanistan storymap don't match with the sides of the screen

### ISSUE THREAD

**Issue by MarionPlanque** [fxi/map-x-mgl#65]
**Current behavior:**

When using a big screen to visualize the Afghanistan storymap, the slides don't match with the sides of the screen: they are not at the place they are supposed to be. 

**Detailed Description**

There is a gap between the slide side and the screen side, and while scrolling down the storymap, the gap becomes bigger and bigger. The result is the following: while switching to the next step, the bottom of the slide of the previous step appears on the screen, also the last slide can not be visualized as it's too "low" compared to the screen.

**Expected behavior:** 

The location of the slides on the screen is the same on all the screens used to visualize storymaps. While switching to the next step, the slide of the previous step doesn't appear on the screen.

**Possible Solution**

**Steps to Reproduce**

**Comment by fxi** [comment]
Thanks. 

Are you using the latest test version (/app/test) ?
Can you make a screenshot, maybe annotated ? 
I currently test screens from iPhone 5 to 24" monitor, but the story map should be resolution independent. The final version will also feature responsive text/content layout, which is not yet implemented. Mostly a CSS/designer job.

**Comment by thomaspiller** [comment]
We noticed with Antonio and Marion that there is a shift in the story map when one uses F11 to have a full screen presentation. The problem may be there.

**Comment by fxi** [comment]
@MarionPlanque please make sure to include important detail such as one mentioned by @thomaspiller. If I'm not able to reproduce a bug, it will not be solved. 

So, I will make something to detect screen size modification during a story map and update all the box calculation. This was not expected, but apparently people do it.

FYI : in the meantime, map-x has a built-in fullscreen feature that will take care of everything.

**Comment by MarionPlanque** [comment]
@fxi Actually before Antonio and Thomas noticed it, I didn't understand it was a problem a full screen presentation, I thought it was just a problem when switching from a screen size to another...
Do you still need some screenshots with comments to illustrate the bug? I can send you the most obvious bugs that appear on the screen

**Comment by fxi** [comment]
@MarionPlanque Yes, this is a problem with changing screen size during a presentation: configuration (slides size, 3d effects parameters, etc..) is done once when we launch the story. 
So, for now, screen size should be set before launching a story map : e.g. pressing the fullscreen button in map-x. Il will update the code to detect the screen size changes.
And no, I don't need a screenshot anymore, @thomaspiller described quite well the issue.
