### ISSUE TITLE
Feature request: legend visualization for WMS raster data

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#68]
### Expected Behavior
When loading a dataset through WMS request, it would be useful to understand what colors refer to in terms of numbers. 
### Current Behavior
Colors are difficult to understand as even the range of data is not known.

### Possible Solution
The visualization of a legend would be enough if data cannot be accessed and therefore information cannot be obtained by clicking on the map (through the pop-up window).

### Steps to Reproduce
1. Load a WMS view according to this code:
https://sedac.ciesin.columbia.edu/geoserver/wms?bbox={bbox-epsg-3857}&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&style=&layers= gpw-v4:gpw-v4-population-count-adjusted-to-2015-unwpp-country-totals_2020&format=image/png8&transparent=true&height=256&width=256 
2. Check its visualization
3.
...

![feat req wms raster legend](https://user-images.githubusercontent.com/30286565/29767896-77990cfc-8be4-11e7-9b75-71aef6cb54b8.JPG)

**Comment by fxi** [comment]
Done:

![mx_add_wms](https://user-images.githubusercontent.com/1196833/29833072-8105b1a8-8cea-11e7-877a-bd6be19cd1af.gif)
