### ISSUE TITLE
WMS generator: SSL connect error

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#70]
I get an error message when using this URL into the WMS generator.

https://unosatgis.cern.ch/data/services/OT20151123ID/Landcover_AOI1_7August2005/MapServer/WMSServer

![selection_001](https://user-images.githubusercontent.com/19908801/30055383-8a88aeac-922f-11e7-8eee-b084904d2149.png)

**Comment by antobenve** [comment]
@thomaspiller , is this still a problem?

**Comment by thomaspiller** [comment]
No, it's fixed.
