### ISSUE TITLE
Story maps problem at configuration (it uses steps from other story maps)

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#74]
### Expected Behavior
No step should be shown in the configuration panel of a story map, when configuring a story map for the first time.

### Current Behavior
The steps from another story map are shown in the configuration panel of a story map when this is configured for the first time.
#
### Steps to Reproduce

1 .I create a story map. The story map is empty and virgin apparently.
2. I configure it for the first time. I find that steps are already present and contains the information of another story map. 
3. If I "upload" the configuration of the view, the view becomes like the one from which the steps were copied. If I only close the configuration window, the view remains virgin.

### Detailed Description
The problem seems related to the fact that I have previously opened the story map from which the steps were later copied. However, the problem does not occur systematically.

**Comment by fxi** [comment]
Is this still an issue in /test ?

**Comment by antobenve** [comment]
It seems that the problem does not occur anymore. My tests were all positives.
