### ISSUE TITLE
Layer is not displayed

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#8]
### Current Behavior

Layer Colombie-corruption is not displayed 
### Steps to Reproduce

1.
2.
3.
...

**Comment by fxi** [comment]
Is this happening on every zoom levels ?

**Comment by alejandraarango** [comment]
Depend on the scale. 
Layer corruption and child labour in Congo and Colombia presented the same issue.

**Comment by fxi** [comment]
I've removed the views presenting one value per country, as they will be part of a new global view category. The views used a scale with only one value : there is no visual variability across the polygon that represents the country, which does not make much sens in a cartographical representation of a country, at a country scale. 

Then, I was not able to reproduce this issue. Maybe something related to our server failure.

Fell free to reopen it if needed.
