### ISSUE TITLE
Duplicated point geometry

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-mgl#86]
There is a duplication of points in "ASGM field studies in eastern DRC (4 sites)" [DRC]
The problem is visible only at certain zoom levels.
![selection_001](https://user-images.githubusercontent.com/19908801/30596878-ba643dfe-9d55-11e7-8212-f48e2c64ccec.png)
![selection_002](https://user-images.githubusercontent.com/19908801/30596882-bceef186-9d55-11e7-8562-cd64972c47ef.png)

**Comment by antobenve** [comment]
I close it as it was a duplicate of an issue and it seems to be solved in any case.
