### ISSUE TITLE
Wrong tooltip description for the transparency tool of WMS views

### ISSUE THREAD

**Issue by nicolasray** [fxi/map-x-mgl#88]
Within WMS views, the first icon (the wheel) allows you to change the transparency of the layer, but the tooltip description when you hover over the wheel says "Search and filter". It should rather read "Transparency".

**Comment by fxi** [comment]
Maybe "settings","tools" or "preferences" could be more appropriate, as other sliders and filters are present here when available. But another dedicated space could be allocated for transparency slider. There is a lot of buttons already. If you have an idea, please write it down.

**Comment by nicolasray** [comment]
Yes, "Settings" would be indeed appropriate.
