### ISSUE TITLE
Impossible to upload layers

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#9]
### Current Behavior

Impossible to upload layers

### Steps to Reproduce

1. Drag layer
2. Clik on “upload this GeoJSON”
3.
...

**Comment by fxi** [comment]
Thanks.

Is this happening with every layer ? 

I can't test right now.

**Comment by alejandraarango** [comment]
Yes, is happening with every layer

Yes, you can test

**Comment by fxi** [comment]
I meant.. I was not in front of a computer, so it was quite difficult to test :)

It was a server issue, closing this.

Thanks for reporting.
