### ISSUE TITLE
Impossible to update style

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#91]
### Current Behavior
Impossible to update color of the last value of the layer. See image

<img width="1280" alt="capture d ecran 2017-09-22 11 26 43" src="https://user-images.githubusercontent.com/28750477/30794603-764f56a8-a1c9-11e7-84a0-f60fa450f97f.png">

**Comment by fxi** [comment]
Can you copy and paste the style rules in json format?

**Comment by alejandraarango** [comment]
{
  "rules": [
    {
      "value": 0,
      "label_en": "No data",
      "label_fr": "",
      "label_es": "",
      "label_ru": "",
      "label_zh": "",
      "label_de": "",
      "label_bn": "",
      "label_fa": "",
      "color": "#999999",
      "opacity": 0.7,
      "size": 1,
      "sprite": "none"
    },
    {
      "value": 5000,
      "label_en": "5.000 - 37'999.999",
      "label_fr": "",
      "label_es": "",
      "label_ru": "",
      "label_zh": "",
      "label_de": "",
      "label_bn": "",
      "label_fa": "",
      "color": "#89a3d9",
      "opacity": 0.7,
      "size": 1,
      "sprite": "none"
    },
    {
      "value": 38000000,
      "label_en": "38'000.000 - 149'999.999",
      "label_fr": "",
      "label_es": "",
      "label_ru": "",
      "label_zh": "",
      "label_de": "",
      "label_bn": "",
      "label_fa": "",
      "color": "#0129ff",
      "opacity": 0.7,
      "size": 1,
      "sprite": "none"
    },
    {
      "value": 150000000,
      "label_en": "150'000.000 - 345'000.000",
      "label_fr": "",
      "label_es": "",
      "label_ru": "",
      "label_zh": "",
      "label_de": "",
      "label_bn": "",
      "label_fa": "",
      "color": "#f1f3d7",
      "opacity": 0.7,
      "size": 1,
      "sprite": "none"
    }
  ]
}

**Comment by fxi** [comment]
Have you tried on the latest version ? I can't reproduce this.

**Comment by alejandraarango** [comment]
I'm working in this version: https://app.mapx.org/
