### ISSUE TITLE
Connection via PostGIS

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#92]
### Current Behavior
I cannot connect via PostGIS to the platform

**Comment by fxi** [comment]
Ok. Which url are you using? cc @thomaspiller

**Comment by alejandraarango** [comment]
https://app.mapx.org/

**Comment by fxi** [comment]
@thomaspiller, if you solve issues or get piece of info by email, please do the follow up in the corresponding issue in github, thanks.

For me, it's an IT issue : postgres is reachable only on the same network and via VPN for security reason.
