### ISSUE TITLE
Feature request: Implementation of Pachto language in MAP-X (Priority 2)

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#94]
Language should be implemented by November 2017 please.

**Comment by antobenve** [comment]
Most is done, but still there are some buttons which label should be translated and the collections' terms which are still in english.

**Comment by antobenve** [comment]
@PierreLacroix , is the pachto language ok in MapX or still to be partly addressed?

**Comment by PierreLacroix** [comment]
You can close the issue. It is project-related, final report has been sent
