### ISSUE TITLE
Pop-up window (at click on features) is disabled for views for which the dashboard was implemented

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#97]
Views for which the dashboard has been implemented do not allow one to use the pop-up window.
It is therefore impossible to interactively select features to be shown on screen on the basis of specific variables from the attribute table that are not used for the styling.

### Possible Solution
Disable the pop-up window only when the dashboard button is selected.

**Comment by fxi** [comment]
Good point. It was a choice, but I agree with the issue.
Next move : popup enabled anytime, button to disable it.
